### ISSUE TITLE
关于ddns无法获取正确远程ip的问题（koolddns/dnspod）

### ISSUE THREAD

**Issue by ikelvingo** [koolshare/ledesoft#1]
a.com通过dnsmasq指定局域网ip用于内网访问，通过ddns+dmz暴露于外网，用于外网访问。
使用whatismyip.akamai.com可以获取正确外网ip，但在ddns中，可能由于dnsmasq优先级较高，远程ip每次都被覆盖为内网ip。理论上应该无视dnsmasq结果直接使用whatismyip.akamai.com返回结果即可。
在lede 1.9中，该问题不存在，启用koolddns，使用同样配置，可以正常获得正确的外网ip并更新。

**Comment by fw867** [comment]
由于koolddsn的存在，目前软件中心的一些ddns插件没有仔细的校对，只是勉强可用的阶段，考虑移除。
