### ISSUE TITLE
使用LEDE，页面显示国内国外都打勾，但是无法上google

### ISSUE THREAD

**Issue by niexingithub** [koolshare/ledesoft#104]
请问这是LEDE哪里限制了吗？

**Comment by leglo** [comment]
dns的问题

**Comment by bilijinshi** [comment]
同样问题，如何解决啊？在插件设置里面换了不同dns配置，还是不行啊

**Comment by djlq** [comment]
代理运行状态国外链接 【2018-07-09 11:55:46】 ✓ 国内链接 【2018-07-09 11:55:46】 ✓

一样上不去啊，哎

**Comment by niexingithub** [comment]
dns设置成什么好啊？
