### ISSUE TITLE
请问一下作者LEDE软件中心是不开源的么?

### ISSUE THREAD

**Issue by monlor** [koolshare/ledesoft#114]

**Comment by wi1dcard** [comment]
刚买了个软路由，卖家强行刷了 Koolshare 的 LEDE 于是研究了下... 看了看代码，关键部分都经过了混淆，🤨不禁怀疑... 难不成我是第一个发现这个问题的人？随后来看 Issues，果然有人问过，然而被直接 Close 了。

唉。
