### ISSUE TITLE
使用非常正常，有两个小问题请教一下

### ISSUE THREAD

**Issue by ndmouse** [koolshare/ledesoft#115]
关于Openwrt V2ray，我用的GWLIST模式，正常情况下应该不会走BT流量的吧？可是我看服务器端日志有明显BT流量的日志。因为这个服务器是阿里云的，限速1M，走BT流量会影响上网，请问有没有办法解决？
第二个是我还有个EXPRESSVPN，已经在路由设置连通，但是没有找到你这个插件一样好的应用方式，请问能否加个功能指定出口（如果有多个服务器还可以做线路冗余了）。如果没有时间请指教我自己设置IPTABLES和路由能否替换插件指令？应该如何做？
非常感谢你的插件，很好用。

**Comment by houzi-** [comment]
可能是你的BT下载那个地址刚好在GFWLIST的IP集合里，你可以把这个BT的下载地址加到例外IP集合里(相当于访问控制的白名单)

**Comment by ndmouse** [comment]
@houzi- 这个我查过了，可以确定四个站hdsyk,htcmct,keepfrds,chdbits都不在gwlist里面。
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/maintain_files/gfwlist.conf
我是在这个网址核对的，不知道是不是这个网址不全？
另外请问你知道纽约时报手机版怎么设置吗？我如果开了全局或者大陆白名单模式就可以看到新闻，GWLIST模式就不行了。
