### ISSUE TITLE
v2ray服务器掉线后路由器所有的国外站点全部打不开

### ISSUE THREAD

**Issue by kania1983** [koolshare/ledesoft#117]
v2ray for openwrt - 0.7-0.8 都存在的bug 重现方式: 客户端gfwlist 方式 v2ray服务器掉线停止或者被墙, 客户端路由器所有的国外站点全部打不开,浏览器状态栏提示:正在解析.国内网站不受影响

**Comment by ndmouse** [comment]
这不是BUG，国外网站走的是8.8.8.8，而8.8.8.8走的是v2ray。。。所以解析不到了。建议你在DNS设置里改成国内优先试试。

**Comment by kania1983** [comment]
昨晚看到回复试了下,在DNS设定里改成国内优先,然后停止v2ray服务器,国内国外都可以了,现在又试了下,还是可以的,用的v2ray官方默认配置文件,v2ray for openwrt - 0.8也是默认设置.
    你可以在附加设置里一键升级V2Ray版本试一下
