### ISSUE TITLE
Zerotier启动失败 Lede v2.19 LEDESoft v0.3.4

### ISSUE THREAD

**Issue by yangleitj** [koolshare/ledesoft#118]
2018年08月02日 00:07:24 ============================================
2018年08月02日 00:07:24 Koolshare LEDE X64 软件中心 zerotier
2018年08月02日 00:07:24 ============================================
2018年08月02日 00:07:24 关闭主服务
2018年08月02日 00:07:24 开始检测固件内zerotier支持环境
2018年08月02日 00:07:24 =====================================================
2018年08月02日 00:07:24 获取支持环境最新版本信息
2018年08月02日 00:07:30 最新版本信息已成功获取，准备下载安装
2018年08月02日 00:07:30 安装支持环境-1
2018年08月02日 00:07:30 安装支持环境-1失败，你的网络可能有问题，请重试！

**Comment by JurryFong** [comment]
你的问题解决了吗?

**Comment by nkcfc** [comment]
这到底是怎么回事呢？网络一切正常，有没有日志呢，想自己分析下。
