### ISSUE TITLE
软件中心dnspod ddns无法使用

### ISSUE THREAD

**Issue by ikelvingo** [koolshare/ledesoft#12]
软件中心的dnspod ddns安装并启用后，报告域名无法解析。
以下是重启lede后产生的相关系统日志：
Mon Aug 28 12:33:48 2017 daemon.notice procd: /etc/rc.d/S98dnspod.sh: /koolshare/scripts/dnspod_update.sh: line 122: /koolshare/bin/wget: not found
Mon Aug 28 12:33:48 2017 daemon.notice procd: /etc/rc.d/S98dnspod.sh: cat: can't open '/tmp/ddnspod': No such file or directory
Mon Aug 28 12:33:48 2017 daemon.notice procd: /etc/rc.d/S98dnspod.sh: /koolshare/scripts/dnspod_update.sh: line 131: /koolshare/bin/wget: not found
Mon Aug 28 12:33:48 2017 daemon.notice procd: /etc/rc.d/S98dnspod.sh: cat: can't open '/tmp/ddnspod': No such file or directory
Mon Aug 28 12:33:48 2017 daemon.notice procd: /etc/rc.d/S98dnspod.sh: added record 
Mon Aug 28 12:33:48 2017 user.notice root: [Dnspod]:2017-08-28 12:33:48 failed
Mon Aug 28 12:33:03 2017 user.notice root: [软件中心]: 启动Dnspod！
Mon Aug 28 12:33:04 2017 daemon.notice procd: /etc/rc.d/S99eqos: uci: Entry not found
Mon Aug 28 12:33:04 2017 daemon.notice procd: /etc/rc.d/S99eqos: uci: Entry not found
Mon Aug 28 12:33:04 2017 daemon.notice procd: /etc/rc.d/S99shadowsocks: uci: Entry not found

**Comment by fw867** [comment]
已修复
