### ISSUE TITLE
Brook更新后还是不能使用

### ISSUE THREAD

**Issue by wztx** [koolshare/ledesoft#124]
看似启动正常，实则无法使用，缺省规则无法更改，老问题依旧

先申明服务器是正常的，手机用APP连接可以直接出墙

【2018年08月17日 17:30:25】: ---------------------- LEDE 固件 brook -----------------------
【2018年08月17日 17:30:25】: brook符合启动条件！~
【2018年08月17日 17:30:25】: 删除 brook 相关的名单配置文件.
【2018年08月17日 17:30:25】: 尝试先清除已存在的iptables规则，防止重复添加
【2018年08月17日 17:30:26】: 先清空已存在的ipset名单，防止重复添加
【2018年08月17日 17:30:26】: 清除重复的ip rule规则.
【2018年08月17日 17:30:26】: 删除ip route规则.
【2018年08月17日 17:30:26】: 清除firewall中相关的 brook 启动命令...
【2018年08月17日 17:30:26】: 关闭 brook 进程...
【2018年08月17日 17:30:26】: 关闭 redsocks2 进程...
【2018年08月17日 17:30:26】: 关闭 dnsforwarder 进程...
【2018年08月17日 17:30:26】: ---------------------------------------------------------------------------------------
【2018年08月17日 17:30:26】: 检测到你的 brook 服务器地址已经是IP格式：1xx.1xx.1xx.1xx,跳过解析...
【2018年08月17日 17:30:26】: 创建国内CDN解析优化配置文件
【2018年08月17日 17:30:26】: 创建国外GFW解析优化配置文件
【2018年08月17日 17:30:27】: 创建状态检测解析优化配置文件
【2018年08月17日 17:30:27】: DNS解析方案国外优先，优先解析国外DNS.
【2018年08月17日 17:30:27】: 添加nat-start触发事件...
【2018年08月17日 17:30:27】: 开启 brook 主进程...
【2018年08月17日 17:30:27】: 开启 redsocks2 主进程...
【2018年08月17日 17:30:27】: 开启 dnsforwarder 主进程...
【2018年08月17日 17:30:27】: 加载nat规则!
【2018年08月17日 17:30:27】: 尝试先清除已存在的iptables规则，防止重复添加
【2018年08月17日 17:30:28】: 先清空已存在的ipset名单，防止重复添加
【2018年08月17日 17:30:28】: 清除重复的ip rule规则.
【2018年08月17日 17:30:28】: 删除ip route规则.
【2018年08月17日 17:30:28】: 创建ipset名单
【2018年08月17日 17:30:28】: 写入iptables规则到nat表中...
【2018年08月17日 17:30:28】: 加载ACL规则：所有模式为：大陆白名单模式
【2018年08月17日 17:30:28】: 开启chromecast功能（DNS劫持功能）
【2018年08月17日 17:30:28】: 重启dnsmasq服务...
【2018年08月17日 17:30:28】: ------------------------- brook 启动完毕 ---------------

**Comment by ivanxxxx** [comment]
更新到2.2版本以后，也是不能使用brook，后来发现是redsocks2无法启动造成的
奇怪的是酷软brook的日志跟你上面写的一样，没任何错误

解决办法：
root@Openwrt:~# ps |grep redsocks2
如果没有出现任务pid，继续执行

root@Openwrt:~# redsocks2 -v
提示一堆文件找不到，其中第一个就是libevent-2.0.so.5，如果是这样，恭喜你，也许能解决

root@Openwrt:~# ln /usr/lib/libevent-2.1.so.6.0.2 /usr/lib/libevent-2.0.so.5

然后重启路由器

重启后用ps确认brook，redsocks2, dnsforwarder三个进程都有执行，应该就可以了

还有就是酷软brook，帐号设置页面最下面

**Comment by wztx** [comment]
感谢回复，按照你给的方法试了，进程也都在运行了，可还是不行
root@Home:~#  ps |grep redsocks2
10972 root      3092 S    grep redsocks2
root@Home:~# ps | grep brook
11142 root      3092 S    grep brook
root@Home:~# ps | grep dnsforwarder
11410 root      3092 S    grep dnsforwarder

**Comment by houzi-** [comment]
这个问题我们会修复的

**Comment by ivanxxxx** [comment]
> 感谢回复，按照你给的方法试了，进程也都在运行了，可还是不行
> root@Home:# ps |grep redsocks2
> 10972 root 3092 S grep redsocks2
> root@Home:# ps | grep brook
> 11142 root 3092 S grep brook
> root@Home:~# ps | grep dnsforwarder
> 11410 root 3092 S grep dnsforwarder

运行
dig @127.0.0.1 -p 7953 www.google.com

如果执行成功应该是能翻的，执行不成功就是dns还没正常

brook模式的dns解析稳定性感觉就是一般般
