### ISSUE TITLE
随着梅林的shadowsocks项目转移，规则更新地址需要修改了

### ISSUE THREAD

**Issue by syuraking** [koolshare/ledesoft#127]
麻烦修改一下koolss和v2ray的规则更新地址为：
url_main="https://github.com/hq450/fancyss/raw/master/rules/"

koolss可以自己改改，V2加密了ELF，望修改一下。
暂时V2ray只能通过SS更新后，手工复制到对应目录下处理

**Comment by jijg1022** [comment]
@syuraking 请教一下在哪里修改koolss的规则更新路径呢？我也发现好久没更新了

**Comment by xiangzl64** [comment]
咋更新呢，规则更新不了强迫症看着难受。

**Comment by ugist** [comment]
@jijg1022 @xiangzl64 

```/koolshare/scripts/ss_rule_update.sh```

第七行 **url_main** 地址修改下。

**Comment by xiangzl64** [comment]
非常感谢，已经可以更新了。

**Comment by jijg1022** [comment]
@ugist 感谢你

**Comment by tenhow** [comment]
谢谢提供网址和路径，写了个脚本来改
ssh 后一起复制粘贴执行可以达到相同效果

```
ss_rule_url="https://github.com/hq450/fancyss/raw/master/rules/"
ss_rule_path="/koolshare/scripts/ss_rule_update.sh"

sed "/url_main=/d" -i ${ss_rule_path}
sed "/url_back=/a\\url_main=\"${ss_rule_url}\"" -i ${ss_rule_path}
```
