### ISSUE TITLE
LEDEv0.3.4中V2Ray插件如下设置，局域网中其他设备还是无法连接。 

### ISSUE THREAD

**Issue by yangleitj** [koolshare/ledesoft#128]
"inbound": {
    "port": 2333,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
    }

**Comment by zxjack** [comment]
你将port改一下试试看。我的配置是可以用的，如下供参考
```
"inbound": {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",  
      "settings": {
        "auth": "noauth",
        "udp": true
      }
```
