### ISSUE TITLE
udp2raw和UDPspeeder在软件中心的描述

### ISSUE THREAD

**Issue by wangyu-** [koolshare/ledesoft#13]
首先非常感谢作者集成我写的udp2raw和UDPspeeder.

我注意到软件中心里对udp2raw和UDPspeeder的描述都是`udp加速`。觉得这样有可能使用户搞不懂两个软件的区别。

udp2raw不是通常意义上的加速器。建议把udp2raw的描述改成`应对udp 限速(qos)、udp断流、udp屏蔽`之类的。也可以保留`udp加速`关键字，再补充说明这个软件主要是应对udp qos的。

谢谢。

==updated==
>也可以保留`udp加速`关键字，再补充说明这个软件主要是应对udp qos的。

这个说明现在也有，但是要安装以后才能看到。貌似还是改了软件中心里的描述比较好。

**Comment by fw867** [comment]
非常感谢你的建议，出于美观和考虑，在软件中心图标上是简述，可能不能完全表达插件的功能，但在安装好插件后，插件配置页会有非常详尽的说明和作者信息。另外非常感谢你开发了这么优秀的开源软件！

**Comment by sadoneli** [comment]
@wangyu- 非常感谢这么好用的软件，考虑给这两兄弟搞个logo不？哈哈

**Comment by wangyu-** [comment]
>非常感谢你的建议，出于美观的考虑，在软件中心图标上是简述，可能不能完全表达插件的功能，但在安装好插件后，插件配置页会有非常详尽的说明和作者信息

好的。

>考虑给这两兄弟搞个logo不

只会写代码，不会美工，暂时先裸奔吧= =。
