### ISSUE TITLE
koolss 新版本有问题，路由器本身不走ss!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by tenhow** [koolshare/ledesoft#143]
我发现，koolss 新版本有问题，路由器本身不走ss!!!!!!!!!!!!!!!!!
排除固件原因，因为我重刷了2.15 2.19 2.20，只装 koolss，都是这样！
iptables 是不是哪里修改过？？？？？

**Comment by TBQin** [comment]
是的，我也发现了.2.19开始升级后SS不走，二级路由器也不走，搞得我只能降级回2.17，希望能解决这个BUG，不然新固件用不了啊

**Comment by TBQin** [comment]
好像搞定了 你在借口那里删除wan6的试试

**Comment by tenhow** [comment]
我昨天回到了2.13， 我没有2.17，我试过的2.15，2.18都不行。然后一番配置，配置好了。硬盘对拷备份以后，看到有2.21了才升级，发现2.21也可以了。建议备份后升级。

**Comment by imEgo** [comment]
2.19版本，我遇到的情况原因是IPv6导致的。PPPOE拨号后获取了IPv6的地址，ping了下Google，发现ping的是IPv6的地址，禁用了PPPOE获取IPv6地址，之后一切正常

**Comment by fw867** [comment]
除了检测和更新的地址，路由器其它的流量都不走ss,避免一些奇怪的问题

**Comment by cos003** [comment]
2.2.2 不支持路由器上外网；而且显示外网也是绿勾，真是无语，为什么。？
