### ISSUE TITLE
koolproxy和koolss冲突

### ISSUE THREAD

**Issue by service1234** [koolshare/ledesoft#144]
开启koolproxy后，koolss显示连接成功，但是获取不到外部地址，连接不了

**Comment by fw867** [comment]
会在下个版本修复

**Comment by HiyungXu** [comment]
手动临时处理方式，在koolss的自定义dnsmasq手动加入以下代码，其他不能访问网站类似，koolproxy截取了koolss的ipset设置
ipset=/www.youtube.com/gfwlist
ipset=/www.google.com/gfwlist
