### ISSUE TITLE
2.21 miniUPnP失效，用户群多名用户表示相同症状，附日志

### ISSUE THREAD

**Issue by Mosney** [koolshare/ledesoft#145]
具体表现为活动的 UPnP 重定向一直为空，然而实际上此时transmission/微信等软件无法设置UPnP端口重定向。   
附图为两次启动后miniUPnP的日志输出。日志中错误提示中的/var/run/miniupnpd.leases这个UPnP租约文件不存在
![image](https://user-images.githubusercontent.com/22477230/45698029-ace6d700-bb99-11e8-9924-5c4bac17879d.png)

**Comment by alepennyq** [comment]
同样的问题
Thu Sep 20 15:40:54 2018 daemon.err miniupnpd[4961]: could not open lease file: /var/run/miniupnpd.leases
Thu Sep 20 15:40:54 2018 daemon.notice miniupnpd[4961]: HTTP listening on port 5000
Thu Sep 20 15:40:54 2018 daemon.warn miniupnpd[4961]: no HTTP IPv6 address, disabling IPv6
Thu Sep 20 15:40:54 2018 daemon.notice miniupnpd[4961]: Listening for NAT-PMP/PCP traffic on port 5351
Thu Sep 20 15:40:54 2018 daemon.err miniupnpd[4961]: PCPSendUnsolicitedAnnounce() IPv6 sendto(): Bad file descriptor
