### ISSUE TITLE
软件中心安装FTP服务器，访问就重启

### ISSUE THREAD

**Issue by wztx** [koolshare/ledesoft#147]
更新到2.0再到2.2都是这个问题
安装好FTP服务器，点进页面开启时正常，只要一访问21端口，系统马上重启，重启后就再也无法点进FTP的页面，也不能访问21端口，一访问又重启

**Comment by wztx** [comment]
卸载也只下手动下载uninstall卸载

**Comment by wztx** [comment]
反复安装卸载，都是如此问题

**Comment by Xiumie** [comment]
在 N3710 v2.22 2.23 同样遇到了
