### ISSUE TITLE
[TinyFecVPN for LEDE - 游戏加速器 0.4] 这个插件有人正常工作过吗？

### ISSUE THREAD

**Issue by fejich** [koolshare/ledesoft#149]
服务器端，编译了无限制版本

插件也显示 国内/外 连接正常

然而通过这个路由器联网的设备，是根本无法上网的。加速无从谈起。

测试下来发现路由器运行完这个插件后，自身是能够连接到国外网站的。在路由器诊断页面里边能 ping 通 Google。

有正常用上这个插件的，能分享下经验吗？
如今我通过在加速模式选择 “自定义黑名单 ” 再配合 KoolSS  的游戏模式或者 Koolgame 来使用这个插件

**Comment by fw867** [comment]
已经完全重写
