### ISSUE TITLE
VPN全家桶脚本希望添加重启dnsmasq部分

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#151]
从2.2x开始，vpn全家桶启动或者配置完之后，提交应用后，网页无法打开，表现为dns错误，手动重启dnsmasq后恢复正常，此问题在我机器上可重现。

个人认为脚本末尾和koolss等插件一样添加重启dnsmasq服务比较好。

**Comment by fw867** [comment]
最好是改好PR,我来合并，插件太多，维护不过来

**Comment by hxjs123** [comment]
学着其他插件的排版试着改了，自己试验成功，已提交pr #152

**Comment by hxjs123** [comment]
试着修改添加了重启dnsmasq服务 #152 。插件页面提交之后，上网正常。

但是，SE-VPN Server Manager导入配置文件操作之后，问题依然出现，依然域名解析问题。这我就不懂原因了。望有空了解一下。
