### ISSUE TITLE
v2ray 插件 劫持 子网 所有 53端口访问到路由的问题

### ISSUE THREAD

**Issue by liumailong** [koolshare/ledesoft#157]
@fw867 兄，我发现  v2ray 会在 NAT 表中，劫持所有的 53 的访问。
![default](https://user-images.githubusercontent.com/10376283/46869873-aa596380-ce5f-11e8-9513-8d5ac9587d34.png)
大概能理解这么做目的，但这并不是必须，用户默认都是从 DHCP 中活得 DNS 地址，插件已经能很好的工作了。

而且还有可能给用户舔麻烦，比如有的应用会使用私有 DNS、比如需要分析DNS 以便除错，以及内网有多网关的情况 等等。

还有这条规则在插件关闭后并没有被删除，只有手动清除才行。

建议：删除这个规则，要保留也得在插件提供相应的开关。

另外： 配置脚本v2ray_config.sh  是加密了吗？我想手动修改都不行。

**Comment by yxmline** [comment]
v2ray_config.sh不是bash脚本文件是elf linux可执行文件改不了，需要源码才能修改
