### ISSUE TITLE
希望给v2ray 插件加入如下功能。

### ISSUE THREAD

**Issue by youwei5683** [koolshare/ledesoft#158]
1.希望加入远程加载配置文件功能：官方文档是： ./v2ray -config https://xxxx.com/config.json
2.希望加入如ss插件一样可以选择服务器实现多服务器切换。
个人觉得可以以 tag 的形式实现。

**Comment by WayneTheKing** [comment]
3.希望加入回国模式。

**Comment by fw867** [comment]
远程配置文件稳定性没有保障吧
