### ISSUE TITLE
LEDE的koolss或者V2Ray能不能麻烦加入回国模式呢

### ISSUE THREAD

**Issue by wsyccc** [koolshare/ledesoft#163]
因为在海外所以想翻墙回国看国内的视频，能不能直接从梅林上copy过来呢？

**Comment by WayneTheKing** [comment]
同求回国模式

**Comment by wsyccc** [comment]
把大陆白名单改成回国模式了，其他模式能不能用没测试。反正回国模式还可以将就能用，除了域名白名单和黑名单莫名抽风（域名交给Google解析的，当时还好用过一会就不过滤了），可以不用域名规则用IP好了。两个DNS也得改成回国模式的。
[https://mega.nz/#F!C3gz2axS!Bomq91dhuijFTrAd2oT_HQ](url)

**Comment by dbumiguel** [comment]
未解决，请求重新开启。

**Comment by Nooooby** [comment]
我也很想要回国模式
