### ISSUE TITLE
希望aliddns加入ipv6支持

### ISSUE THREAD

**Issue by AragonSnow** [koolshare/ledesoft#165]
现在都开始分配ipv6了，对于没有公网ipv4的人来说是福音，但是由于现在每次重新拨号以后就更换了一个ipv6，所以希望aliddns能加入对ipv6的支持。

**Comment by AragonSnow** [comment]
我才发现2.23版本是可以运行python的，现在我使用脚本可以实现ddnsv6,开发者可以参考一下
https://github.com/NewFuture/DDNS

**Comment by Droid-MAX** [comment]
aliddns ipv6 android
目前还没找到一个比较好的方案用于在手机上建站，并且通过ipv6来访问，此外ipv6地址都还是动态的，容易变动，不然就不用ddns了，加上域名是在阿里云上注册的，但官方又没有比较好的针对安卓平台的ipv6-ddns解决方案，所以这就给我在手机上建站并通过ipv6方式访问带来了一定的困难
