### ISSUE TITLE
多线路宽带接入,希望支持v2ray

### ISSUE THREAD

**Issue by kania1983** [koolshare/ledesoft#167]
接入 联通跟电信,双wan后,就 不支持了,koolss for OpenWRT  可以 识别策略路由 哪个wan口走国外 就用哪个wan口,v2ray还需要其他设置吗 ,还是 暂时不支持?

**Comment by fw867** [comment]
可以安装路由表设置插件，指定你服务器ip要走的线路

**Comment by havoc123** [comment]
> 可以安装路由表设置插件，指定你服务器ip要走的线路

开了路由表插件后 策略路由插件就没用了 这两个有冲突，有没有两个共存的办法
