### ISSUE TITLE
透明网桥插件发现一处BUG，请修复

### ISSUE THREAD

**Issue by Promix953** [koolshare/ledesoft#171]
看到软件中心上线了透明网桥插件，马上下载试用，发现安装后可以正常上网，但是SS和kp都无法生效
折腾了一晚上最后发现插件版没有对sysctl进行设置。。。

脚本版第05、06行：
```
echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf
```
通过`sysctl -a | grep bridge-nf-call`发现`net.bridge.bridge-nf-call-iptables`没有启用

立马git拉下来想改一下，发现`bridge_config.sh`居然是二进制文件，ELF开头可执行文件。。。这后缀名。。。

提个Issues，希望尽快修复

**Comment by fw867** [comment]
应该是你安装了不受支持的固件，透明网桥需要在2.15固件上才能正常使用

**Comment by Promix953** [comment]
> 应该是你安装了不受支持的固件，透明网桥需要在2.15固件上才能正常使用

使用的是2.24版本，是受支持的。
不知道0.2版本的插件具体修改了那些地方，是否修复这一问题？
