### ISSUE TITLE
科学上网稳的从岸上飘水里去了，我的都快懵了，给点力啊！我很郁闷，你也很心累

### ISSUE THREAD

**Issue by 1225475505** [koolshare/ledesoft#176]

**Comment by 1225475505** [comment]
现在时间：2018年10月20日 22:56:30

**Comment by 1225475505** [comment]
科学上网也是基本的软路由所必备的对吧？开发者大神小哥哥？我咋感觉科学上网老给我玩抽疯，我的心此时痛并快乐着，...........................

**Comment by 1225475505** [comment]
现在时间：2018年10月20日 23:01:22，刚刚恢复正常，希望一直稳定，辛苦了，开发者！如稳，我潜水，如不稳，我会来骚扰你哦，开发者小哥哥！

**Comment by 1225475505** [comment]
我发现了科学上网新大陆？为什么这么说？那是因为的PC端可以科学，路由器不行了，没道理啊！我是从软路由接线到硬路由器上的，咋回事？现在时间：2018年10月20日 23:08:56

**Comment by houzi-** [comment]
找个时间我远程看下你那啥情况
