### ISSUE TITLE
ZeroTier未运行 Openwrt X64 v2.24 LEDESoft v0.3.6

### ISSUE THREAD

**Issue by yangleitj** [koolshare/ledesoft#181]
2018年10月26日 00:33:53 ============================================
2018年10月26日 00:33:53              Koolshare LEDE X64 软件中心 zerotier    
2018年10月26日 00:33:53 ============================================
2018年10月26日 00:33:53 关闭主服务
2018年10月26日 00:33:53 开始检测固件内zerotier支持环境
2018年10月26日 00:33:53 =====================================================
2018年10月26日 00:33:53 获取支持环境最新版本信息
2018年10月26日 00:34:05 最新版本信息已成功获取，准备下载安装
2018年10月26日 00:34:05 安装支持环境-1
2018年10月26日 00:34:10 支持环境-1已安装，检测通过
2018年10月26日 00:34:10 ============================================
2018年10月26日 00:34:10 所有支持环境已经就绪，开始运行
2018年10月26日 00:34:10 开始运行主服务
2018年10月26日 00:34:10 Done!
2018年10月26日 00:34:10 开始配置网络接口ZEROTIER
2018年10月26日 00:34:10 Done!
2018年10月26日 00:34:10 开始配置防火墙
2018年10月26日 00:34:10 Done!
2018年10月26日 00:34:10 开始配置ID
2018年10月26日 00:34:10 等待建立连接15s
/usr/bin/zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
2018年10月26日 00:34:25 Done!
2018年10月26日 00:34:25 ============================================
2018年10月26日 00:34:25 all done enjoy！
2018年10月26日 00:34:25 页面将在3秒后跳转

**Comment by github1-2-3** [comment]
找/etc/config/zerotier文件，把option enabled '0'的0改为1
