### ISSUE TITLE
请教一下dbus的来源

### ISSUE THREAD

**Issue by pzkj** [koolshare/ledesoft#193]
麻烦问一下 代码中的dbus工具 和 进程通信用的dbus 貌似不是同一个东西，这个dbus工具是自己写的吗? 有开源吗?

**Comment by sadoneli** [comment]
不是一个东西
dbus是操作skipdb数据库用的，参见这个http://koolshare.cn/thread-4850-1-1.html
现在已经不开源，版本也比帖子里提到的更新了几代了

**Comment by pzkj** [comment]
> 不是一个东西
> dbus是操作skipdb数据库用的，参见这个http://koolshare.cn/thread-4850-1-1.html
> 现在已经不开源，版本也比帖子里提到的更新了几代了

好的 谢谢
