### ISSUE TITLE
困扰了好久的问题,IPv6 跟 ssr,v2ray的共存兼容

### ISSUE THREAD

**Issue by kania1983** [koolshare/ledesoft#196]
设备说明: 刷的Openwrt X64 V2.25, PC端ipv6获取正常, 浏览ipv6网站正常, ss或者v2ray使用纯ipv6服务器.
再现: 如果禁用PC端ipv6网络,只用ipv4,ss或者v2ray,工作正常.访问谷歌youtube正常.
如果PC端同时使用ipv6和ipv4, ,ss或者v2ray,就不能正常访问谷歌youtube了,访问非被蔷的ipv4和ipv6都正常.
简单猜测:应该是pc端的ipv6网络没有经过路由器的,ss或者v2ray而直接的去访问被蔷的网址,.

请求帮助:那么如何让PC端的ipv6网络,也经过路由器的ss或者v2ray的服务器去访问谷歌youtube?

**Comment by helllkz** [comment]
我也有类似的问题，下面2台机器，1个win10，1个centos，都是IPv4+IPv6
Win10一切正常，centos就不能访问国外了，把centos的IPv6禁用了就能正常出国了，估计是win10的v6优先级比v4低，所以能正常使用

**Comment by elvisw** [comment]
这个主要问题是IPv6不像IPv4那样有NAT，没法透明代理转发。暂时的解决方法是将被墙网站域名解析的IPv6（AAAA）结果全部丢弃，走IPv4透明代理应该就可以。但是我也不知道如何具体实现。
