### ISSUE TITLE
求V2RAY插件可以解析自定义inbound

### ISSUE THREAD

**Issue by youwei5683** [koolshare/ledesoft#199]
求V2RAY插件可以解析自定义inbound:
比如自己定义的：
shadowsocks
http
socks5
这样就可以自定义回家方式了。。谢谢大佬

**Comment by sadoneli** [comment]
插件无法满足所有需求，插件是定位于透明代理的，所以inbound透明代理无法改动

如果有此种需求，建议不用插件，自行配置程序
