### ISSUE TITLE
koolss能否支持一下tcp udp使用不同的线路

### ISSUE THREAD

**Issue by yeheigcy** [koolshare/ledesoft#200]
我使用的ssr提供游戏节点，但不允许大流量，如看视频之类的，然后每次玩游戏都需要登进路由器后台切换节点，所以
1：游戏模式能否让TCP流量走线路A，UDP流量走线路B？
2：全局模式能不能也开启UDP转发？（用的垃圾移动网，部分国内游戏都玩不了，想接入国内的节点玩游戏）也就是将UDP设为一个单独的开关，取消游戏模式。

**Comment by sadoneli** [comment]
玩游戏也不是纯粹的udp，很多认证登录等操作需要tcp的
看视频也不一定就是tcp，youtube等是可以通过udp走quic协议的

这种特殊的需求，即使在插件里做出来但无疑是增加插件复杂度
这恐怕千分之一都不到的需求，就没必要做出来反而影响其它千分之九百九十九的了

特殊需求可以不借用插件，自己实现配置就好

**Comment by yeheigcy** [comment]
好的，我发现写个批处理切换线路挺方便的。
