### ISSUE TITLE
关于KoolSS和ipv6

### ISSUE THREAD

**Issue by hejaxian** [koolshare/ledesoft#201]
今年大家都普及了IPV6，可否考虑了在SS中增加IPV6的部分，反正原来shadowsocks-libev是完全支持IPV6的，实现层面也只是在ip6tables里面增加对应的规则把流量转发到透明代理端口。
1、关于IPV6的chnroute，地址段可以从https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest里面爬取，反正V4V6都一样。
2、如果有精力，建议增加一个功能V4 V6流量可以走不同的节点。

**Comment by sadoneli** [comment]
暂不考虑ipv6
