### ISSUE TITLE
koolddns Secret或者Token(长) 填写位数有限制

### ISSUE THREAD

**Issue by zongheng23333** [koolshare/ledesoft#203]
koolddns插件的填写 Secret或者Token(长)  这一项 填写的位数有限制 我填的了ffd6cd8da4b689d95b4721221523f4    后面还有就填不上了

**Comment by zongheng23333** [comment]
32位

**Comment by zongheng23333** [comment]
> 你的这一项`Secret或者Token(长) `的位数有多少？

32位

**Comment by houzi-** [comment]
已修复
