### ISSUE TITLE
KoolDNS 对于IPv6支撑有问题

### ISSUE THREAD

**Issue by dominicx** [koolshare/ledesoft#210]
【2018年12月25日 13:07:18】: 目标域名: home2.xxxx.com
【2018年12月25日 13:07:18】: 获取网络 pppoe-vwan1 接口  信息出错  
【2018年12月25日 13:07:18】: 
【2018年12月25日 13:07:18】: --------------------------------------------------
【2018年12月25日 13:07:18】: 目标域名: home.xxxx.com
【2018年12月25日 13:07:18】: 获取网络 pppoe-wan 接口  _#信息出错 #没有处理好接口中的ipv6地址信息_
【2018年12月25日 13:07:18】: 
【2018年12月25日 13:07:18】: --------------------------------------------------
【2018年12月25日 13:07:18】: 目标域名: home2.xxxx.com
【2018年12月25日 13:07:18】: 远程解析IP: 60.168.100.34
【2018年12月25日 13:07:18】: 本地指定IP: 60.168.100.34
【2018年12月25日 13:07:18】: 解析地址一致，无需更新
【2018年12月25日 13:07:18】: 
【2018年12月25日 13:07:18】: --------------------------------------------------
【2018年12月25日 13:07:18】: 目标域名: home.xxxx.com
【2018年12月25日 13:07:18】: 远程解析IP: 240e:363:119:dd00::1 _#没有处理好返回的结果中的ipv6_
【2018年12月25日 13:07:18】: 本地指定IP: 117.71.100.65
【2018年12月25日 13:07:20】: koolddns更新成功！
【2018年12月25日 13:07:20】: 

目测getwan 解析wan的ipv6地址失败。
以及调用busybox的nslookup 没有处理ipv6。

**Comment by fw867** [comment]
已修复
