### ISSUE TITLE
gdddns没人维护了，计划执行脚本和API兼容都没改，为啥不合入koolddns 

### ISSUE THREAD

**Issue by 0x5826** [koolshare/ledesoft#217]
gdddns没人维护了，基本处于不可用状态，主要有两个问题：
1、计划执行脚本基本上无效了，不执行
2、狗爹改了API，这个代码也没改
为啥不直接合入koolddns？

**Comment by fw867** [comment]
改了哪些api,能先PR一下吗？

**Comment by fw867** [comment]
已合并

**Comment by tankren** [comment]
gdddns直接删了吗？我以前改过脚本发论坛了但是没有放GitHub上
