### ISSUE TITLE
luci界面的端口修改过之后，必须修改/koolshare/scripts/base.sh文件，不然软件中心安装的软件都无法获取状态

### ISSUE THREAD

**Issue by lm789632** [koolshare/ledesoft#22]
我现在是手动修改 /koolshare/scripts/base.sh 文件第九行
export LANIP=127.0.0.1
为
export LANIP=127.0.0.1:端口
能否自动读取 /etc/config/uhttpd 文件的
list listen_http 这一行的设置？

**Comment by fw867** [comment]
@sadoneli 你觉得有必要适配吗？

**Comment by sadoneli** [comment]
@fw867 可以的

**Comment by lm789632** [comment]
@fw867 @sadoneli  感谢，很期待更新

**Comment by sadoneli** [comment]
所以最后这个我到底更新没？

**Comment by fw867** [comment]
并没有，所以这个一直保留到现在。。。

**Comment by darkrain88** [comment]
我也遇到过 还好bash。sh是可以打开的
