### ISSUE TITLE
v2ray 2.3.1 dns配置引起gfwlist模式下无法访问的问题

### ISSUE THREAD

**Issue by ikelvingo** [koolshare/ledesoft#226]
v2ray 2.3.1
v2ray_dns使用预置的3个dns服务器，gfwlist模式均无法使用；
v2ray_dns使用自定义dns服务器，但输入格式为1.1.1.1:53，gfwlist模式无法使用；
**v2ray_dns使用自定义dns服务器，输入格式为1.1.1.1，gfwlist模式可以使用。**

**Comment by fw867** [comment]
预置的无法使用是因为你的VPS到这三个dns不通，自定义:是英文字符，不要用中文字符输入：
