### ISSUE TITLE
2.3.2升级后原来可以的配置无法通过测试了

### ISSUE THREAD

**Issue by xlarryzhu** [koolshare/ledesoft#227]
【2019年01月10日 22:31:26】: ---------------------- LEDE 固件 v2ray -----------------------
【2019年01月10日 22:31:26】: v2ray符合启动条件！~
【2019年01月10日 22:31:26】: 重启dnsmasq服务...
【2019年01月10日 22:31:30】: 尝试先清除已存在的iptables规则，防止重复添加
【2019年01月10日 22:31:31】: 先清空已存在的ipset名单，防止重复添加
【2019年01月10日 22:31:31】: 清除重复的ip rule规则.
【2019年01月10日 22:31:31】: 删除ip route规则.
【2019年01月10日 22:31:31】: 清除firewall中相关的 v2ray 启动命令...
【2019年01月10日 22:31:31】: 创建国内CDN解析优化配置文件
【2019年01月10日 22:31:31】: 创建状态检测解析优化配置文件
【2019年01月10日 22:31:31】: 应用域名白名单
【2019年01月10日 22:31:31】: DNS解析方案国外优先，优先解析国外DNS.
【2019年01月10日 22:31:31】: 添加nat-start触发事件...
【2019年01月10日 22:31:31】: 优化网络参数
【2019年01月10日 22:31:31】: 使用 xxx 配置文件...
【2019年01月10日 22:31:31】: 解析V2Ray配置文件...
【2019年01月10日 22:31:31】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2019年01月10日 22:31:31】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
【2019年01月10日 22:31:31】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
【2019年01月10日 22:31:31】: 测试V2Ray配置文件.....
【2019年01月10日 22:31:31】: V2Ray配置文件没有通过测试，请检查设置!!!
【2019年01月10日 22:31:31】: 出错原因：Configuration OK.
【2019年01月10日 22:31:31】: 插件将在5秒后自动关闭！！
【2019年01月10日 22:31:32】: 5
【2019年01月10日 22:31:33】: 4
【2019年01月10日 22:31:34】: 3
【2019年01月10日 22:31:35】: 2
【2019年01月10日 22:31:36】: 1
【2019年01月10日 22:31:37】: 0
【2019年01月10日 22:31:41】: 插件已关闭！！
【2019年01月10日 22:31:41】: ------------------------- v2ray 成功关闭 -------------------------
 
{"result":0}

**Comment by xlarryzhu** [comment]
15:02】: 添加nat-start触发事件...
【2019年01月10日 22:15:02】: 优化网络参数
【2019年01月10日 22:15:02】: 使用 xxx 配置文件...
【2019年01月10日 22:15:02】: 解析V2Ray配置文件...
【2019年01月10日 22:15:02】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2019年01月10日 22:15:02】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
【2019年01月10日 22:15:02】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
【2019年01月10日 22:15:02】: 测试V2Ray配置文件.....
【2019年01月10日 22:15:02】: V2Ray配置文件没有通过测试，请检查设置!!!
【2019年01月10日 22:15:02】: 出错原因：Configuration OK.
【2019年01月10日 22:15:02】: 插件将在5秒后自动关闭！！
【2019年01月10日 22:15:03】: 5
【2019年01月10日 22:15:04】: 4

**Comment by fw867** [comment]
TG上M我你的配置，隐藏ID

**Comment by xlarryzhu** [comment]
> TG上M我你的配置，隐藏ID

没墙暂时不了TG，QQ发你消息了

**Comment by xlarryzhu** [comment]
V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
SCP看到/koolshare/v2ray/v2ray.json为空，选择任意节点均可。节点配置为v2rayN（2.21+4.10） windows可用站点的vmess链接导入，之前在2.2及2.3.1可用。LEDE版本2.22

**Comment by fw867** [comment]
测试正常，尝试清除所有节点，再通过链接导入
