### ISSUE TITLE
v2ray配置校验错误

### ISSUE THREAD

**Issue by duguying** [koolshare/ledesoft#228]
![qq 20190111151952](https://user-images.githubusercontent.com/3050360/51019030-828bb000-15b4-11e9-8906-e3122be4a5d3.png)

明明校验成功了，还报错。

**Comment by fw867** [comment]
请升级到最新固件，有些版本的固件jq有bug,无法正确处理json

**Comment by duguying** [comment]
清理了缓存，也没有用的。版本号 2.3.3

**Comment by fw867** [comment]
固件版本？

**Comment by fw867** [comment]
老版本固件不再作支持，请升级到最新固件或者使用旧版本插件

**Comment by duguying** [comment]
用酷软中心里的应用升级固件了，然后路由器挂了，我日……
