### ISSUE TITLE
v2ray会和自己安装的带luci界面的smartdns冲突。

### ISSUE THREAD

**Issue by cjameslynn** [koolshare/ledesoft#233]
不管我有没有在v2ray里使用smartdns，都会自动关闭我的smartdns

**Comment by cjameslynn** [comment]
关闭这个issues指的是这个不重要还是下一版本可以搞定？也不comment一下，我好等等或自己想办法

**Comment by Promix953** [comment]
> 关闭这个issues指的是这个不重要还是下一版本可以搞定？也不comment一下，我好等等或自己想办法

习惯就好，他们从心底里是看不起我们这些用户的，懒得搭理

**Comment by yutaowang** [comment]
好奇，这个服务是付费的吗？
