### ISSUE TITLE
Why this file (anyconnect_config.sh) is not open-source?

### ISSUE THREAD

**Issue by cnpcshangbo** [koolshare/ledesoft#234]
Hi, @fw867 
Is it from Cisco or custom-made?
Thanks,
@cnpcshangbo

**Comment by sadoneli** [comment]
It is custom made, for some specific reason, the source is not plaint text for public.

**Comment by cnpcshangbo** [comment]
Thanks, @sadoneli 
Do you know if this issue https://github.com/koolshare/ledesoft/issues/235 can be solved by downloading something manually? I guess the link address should be in anyconnect_config.sh.

**Comment by cnpcshangbo** [comment]
Thanks.

hxjs123 <notifications@github.com>于2019年1月25日 周五下午11:27写道：
