### ISSUE TITLE
Cisco Anyconnect 安装支持环境-1失败，你的网络可能有问题，请重试！

### ISSUE THREAD

**Issue by cnpcshangbo** [koolshare/ledesoft#235]
2019年01月24日 12:39:36 ============================================
2019年01月24日 12:39:36              Koolshare LEDE X64 软件中心 AnyConnect    
2019年01月24日 12:39:36 ============================================
2019年01月24日 12:39:36 关闭主进程
2019年01月24日 12:39:36 关闭防火墙端口
2019年01月24日 12:39:37 开始检测固件内AnyConnect支持环境
2019年01月24日 12:39:37 =====================================================
2019年01月24日 12:39:37 获取支持环境最新版本信息
2019年01月24日 12:39:47 最新版本信息已成功获取，准备下载安装
2019年01月24日 12:39:47 安装支持环境-1
2019年01月24日 12:39:50 安装支持环境-1失败，你的网络可能有问题，请重试！

**Comment by zcluo** [comment]
我装transmission 也一直这样

zcluo

________________________________
发件人: Bo Shang <notifications@github.com>
发送时间: 星期四, 一月 24, 2019 12:41
收件人: koolshare/ledesoft
抄送: Subscribed
主题: [koolshare/ledesoft] Cisco Anyconnect 安装支持环境-1失败，你的网络可能有问题，请重试！ (#235)


2019年01月24日 12:39:36 ============================================
2019年01月24日 12:39:36 Koolshare LEDE X64 软件中心 AnyConnect
2019年01月24日 12:39:36 ============================================
2019年01月24日 12:39:36 关闭主进程
2019年01月24日 12:39:36 关闭防火墙端口
2019年01月24日 12:39:37 开始检测固件内AnyConnect支持环境
2019年01月24日 12:39:37 =====================================================
2019年01月24日 12:39:37 获取支持环境最新版本信息
2019年01月24日 12:39:47 最新版本信息已成功获取，准备下载安装
2019年01月24日 12:39:47 安装支持环境-1
2019年01月24日 12:39:50 安装支持环境-1失败，你的网络可能有问题，请重试！

―

**Comment by houzi-** [comment]
https://github.com/koolshare/ledesoft/commit/31e6e8c02a37b6771e6d237dec0e86e64814170b
