### ISSUE TITLE
某些老版本固件已经无法使用新版插件,请升级到最新版固件使用!

### ISSUE THREAD

**Issue by Moy4e** [koolshare/ledesoft#237]
从Openwrt Koolshare mod V2.17 升级到	Openwrt Koolshare mod V2.26 r9789-f4b7c27ab5

运行V2RAY 日志提示
某些老版本固件已经无法使用新版插件,请升级到最新版固件使用!

**Comment by alegoho** [comment]
我是升级后SS不能用啊……
