### ISSUE TITLE
Can't download content for docker.

### ISSUE THREAD

**Issue by cnpcshangbo** [koolshare/ledesoft#239]
![image](https://user-images.githubusercontent.com/4831029/52180242-c32ac200-281e-11e9-90ec-b098c6577a33.png)
![image](https://user-images.githubusercontent.com/4831029/52180258-f2413380-281e-11e9-96d7-82a9aa31345d.png)

Any ideas on how to fix this?

**Comment by fw867** [comment]
Waiting or try again
