### ISSUE TITLE
v2ray 插件  ipv6 与自己安装的SmartDNS 兼容性的问题。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [koolshare/ledesoft#240]
目前v2ray 插件，既不能代理v6也不能在DNS层面屏蔽v6的解析。
而游览器会优先访问v6，这样就导致的访问失败。
想了个变通的办法，SmartDNS 能屏蔽v6的解析，把它作为国外地址解析的上游。
这样就能强制代理的地址，只能拿到ipv4地址了。

然而 v2ray 插件，会关闭自己安装的 SmartDNS ，猜测代码直接用了 killall SmartDNS.
希望修复这个BUG。

另外提两个建议。
既然国内DNS 集成了 SmartDNS，不如在国外也带上。
考虑到效率和兼容性，可以启用两个不同配置的SmartDNS

各个插件启用的软件，改为单独的文件名，如v2ray_koolshare，SmartDNS_koolshare之类的。
这样就不冲突了，关闭进程时最好也指定路径。

**Comment by cjameslynn** [comment]
我也是在烦这个问题
