### ISSUE TITLE
请帮忙看一下，运行错误日志。

### ISSUE THREAD

**Issue by Moy4e** [koolshare/ledesoft#241]
【2019年02月06日 19:58:59】: ---------------------- LEDE 固件 v2ray -----------------------
【2019年02月06日 19:58:59】: v2ray符合启动条件！~
【2019年02月06日 19:59:00】: 重启dnsmasq服务...
【2019年02月06日 19:59:03】: 尝试先清除已存在的iptables规则，防止重复添加
【2019年02月06日 19:59:04】: 先清空已存在的ipset名单，防止重复添加
【2019年02月06日 19:59:04】: 清除重复的ip rule规则.
【2019年02月06日 19:59:04】: 删除ip route规则.
【2019年02月06日 19:59:04】: 清除firewall中相关的 v2ray 启动命令...
【2019年02月06日 19:59:04】: 创建国内CDN解析优化配置文件
【2019年02月06日 19:59:05】: 创建国外GFW解析优化配置文件
【2019年02月06日 19:59:05】: 创建状态检测解析优化配置文件
【2019年02月06日 19:59:05】: DNS解析方案国外优先，优先解析国外DNS.
【2019年02月06日 19:59:05】: 添加nat-start触发事件...
【2019年02月06日 19:59:05】: 优化网络参数
【2019年02月06日 19:59:05】: 使用 google 配置文件...
【2019年02月06日 19:59:05】: 解析V2Ray配置文件...
【2019年02月06日 19:59:05】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2019年02月06日 19:59:05】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
【2019年02月06日 19:59:05】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
【2019年02月06日 19:59:05】: 测试V2Ray配置文件.....
【2019年02月06日 19:59:06】: Configuration OK.
【2019年02月06日 19:59:06】: V2Ray配置文件通过测试，但固件版本过低，无法正确解析配置文件，请升级到最新固件！
【2019年02月06日 19:59:06】: 插件将在5秒后自动关闭！！
【2019年02月06日 19:59:07】: 5
【2019年02月06日 19:59:08】: 4
【2019年02月06日 19:59:09】: 3
【2019年02月06日 19:59:10】: 2
【2019年02月06日 19:59:11】: 1
【2019年02月06日 19:59:12】: 0
【2019年02月06日 19:59:16】: 某些老版本固件已经无法使用新版插件，请升级到最新版固件使用！
【2019年02月06日 19:59:16】: 插件已关闭！！
【2019年02月06日 19:59:16】: ------------------------- v2ray 成功关闭 -------------------------
 
{"result":0}

------------------------------
固件版本	Openwrt Koolshare mod V2.26 r9789-f4b7c27ab5
内核版本	4.14.90

**Comment by yutaowang** [comment]
【2019年02月06日 19:59:16】: 某些老版本固件已经无法使用新版插件，请升级到最新版固件使用！

**Comment by Moy4e** [comment]
固件已经升级了。
