### ISSUE TITLE
关于koolddns的问题koolddns for openwrt - 0.6.1

### ISSUE THREAD

**Issue by shep2008** [koolshare/ledesoft#247]
我用的是阿里云解析，域名是第三方的域名，格式是类似koolshare.cn（后面用这个来作示意），不需要前面的“www.”，之前在2.26之前的版本中的koolddns只要设置子域名名称为“@”就可以了，升级了2.26以后koolddns for openwrt放到了插件里，这个设置也不管用了，设置如图1所示，手动更新后显示如图2的错误结果：目标域名: @.\tkoolshare.cn，只有子域名名称设置“*”才可以，这样的结果就是我只能用www.koolshare.cn这种形式来访问！这样非常不方便，然后尽快解决这个问题！谢谢
![image](https://user-images.githubusercontent.com/42241740/52909957-7d183880-32cb-11e9-9b65-708d31ea7345.png)
![image](https://user-images.githubusercontent.com/42241740/52909986-f021af00-32cb-11e9-9e49-bffa3a21b61e.png)
总结一下就是以前可以设置通过“abcd.cn“来访问，现在设置只能通过”www.abcd.cn“来访问

另外还有一个建议，
界面可以像之前的版本一样，可以显示接口IP和远程解析IP如下图，这样主界面就可以看出来有没有更新！
![image](https://user-images.githubusercontent.com/42241740/52910081-565b0180-32cd-11e9-9da1-55b9303e85b3.png)

**Comment by rangerwill** [comment]
尝试更新 openssl-util 和 curl 这两个ipk
