### ISSUE TITLE
koolss插件的ss混淆模式无法使用

### ISSUE THREAD

**Issue by monlor** [koolshare/ledesoft#263]
#### 问题
配置ss混淆时，已关闭mptcp，并写了混淆配置。查看配置文件`/koolshare/ss/ss.json`发现mptcp为true，并没有生成混淆的配置信息。
#### 可能的BUG
* 前端设置为`ssconf_basic_ss_obfs`，而后端取的`ss_basic_ss_obfs`
* `ss_basic_type`在前端并没有设置为1，导致没生成混淆的配置。

**Comment by ppyyr** [comment]
遇到同样的问题, 回退到了Oct 21, 2018版本..

**Comment by Nicepaul** [comment]
我也遇到这个问题了，请把离线文件下载地址发给我一下，谢谢
