### ISSUE TITLE
v2ray_config.sh文件打不开

### ISSUE THREAD

**Issue by johnnyzhangcd** [koolshare/ledesoft#265]
![image](https://user-images.githubusercontent.com/47234845/53718512-627ebb80-3e96-11e9-90ff-f730f41907b9.png)
请问这个shell文件是经过了混淆的吗?为什么不能直接查看?
现在有个需求是要转发10.0.0.0/8的流量到V2RAY透明代理端口.需要修改一下脚本

**Comment by dingleshxt** [comment]
用点小技巧可以解开哈哈哈

**Comment by johnnyzhangcd** [comment]
> 用点小技巧可以解开哈哈哈

求大佬分享. 那个shell脚本是加密的么?

**Comment by dingleshxt** [comment]
> > 用点小技巧可以解开哈哈哈
> 
> 求大佬分享. 那个shell脚本是加密的么?
> 现在其实就需要改一下脚本里面的 white_list
> 我现在是手动的配置
> ipset del white_list 10.0.0.0/8

对的 那个好像用的shc 这个命令加密的，你可以自己试试看吧，具体我感觉作者加密也是有加密的原因

我看到确实有一行是几个白名单的
`
	ip_lan="0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.168.0.0/16 224.0.0.0/4 240.0.0.0/4 $SERVER_IP 223.5.5.5 223.6.6.6 114.114.114.114 114.114.115.115 1.2.4.8 210.2.4.8 112.124.47.27 114.215.126.16 180.76.76.76 119.29.29.29 $ISP_DNS1 $ISP_DNS2"

`

**Comment by johnnyzhangcd** [comment]
> > > 用点小技巧可以解开哈哈哈
> > 
> > 
> > 求大佬分享. 那个shell脚本是加密的么?
> > 现在其实就需要改一下脚本里面的 white_list
> > 我现在是手动的配置
> > ipset del white_list 10.0.0.0/8
> 
> 对的 那个好像用的shc 这个命令加密的，你可以自己试试看吧，具体我感觉作者加密也是有加密的原因，我也不太好说
> 
> 我看到确实有一行是几个白名单的
> `	ip_lan="0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.168.0.0/16 224.0.0.0/4 240.0.0.0/4 $SERVER_IP 223.5.5.5 223.6.6.6 114.114.114.114 114.114.115.115 1.2.4.8 210.2.4.8 112.124.47.27 114.215.126.16 180.76.76.76 119.29.29.29 $ISP_DNS1 $ISP_DNS2" `

那我试试用unshc能解密不.
感谢

**Comment by johnnyzhangcd** [comment]
@dingleshxt 
root@Openwrt:~# ./unshc-v0.8.sh v2ray_config.sh
 _   _       _____ _   _
| | | |     /  ___| | | |
| | | |_ __ \ `--.| |_| | ___
| | | | '_ \ `--. \  _  |/ __|
| |_| | | | /\__/ / | | | (__
 \___/|_| |_\____/\_| |_/\___|

--- UnSHc - The shc decrypter.
--- Version: 0.8
------------------------------
UnSHc is used to decrypt script encrypted with SHc
Original idea from Luiz Octavio Duarte (LOD)
Updated and modernized by Yann CAM
- SHc   : [http://www.datsi.fi.upm.es/~frosal/]
- UnSHc : [https://www.asafety.fr/unshc-the-shc-decrypter/]
------------------------------

[*] Input file name to decrypt [v2ray_config.sh]
./unshc-v0.8.sh: line 140: -D: command not found
./unshc-v0.8.sh: line 142: -s: command not found
[-] Unable to define arc4() call address...
这个 unshc是要安装什么依赖吗?

**Comment by fw867** [comment]
内网地址不应该从白名单里取消，这样会导致nat环回
