### ISSUE TITLE
koolss 2.2.1 cdns进程未启动

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#267]
koolss 2.2.1 cdns进程未启动

Thu Mar  7 08:50:24 2019 kern.info ssr-redir[14641]: initializing ciphers... rc4-md5-6
Thu Mar  7 08:50:24 2019 kern.info ssr-redir[14641]: tcp port reuse enabled
Thu Mar  7 08:50:24 2019 kern.info ssr-redir[14641]: UDP relay enabled
Thu Mar  7 08:50:24 2019 kern.info ssr-redir[14641]: udp port reuse enabled
Thu Mar  7 08:50:24 2019 kern.info ssr-redir[14641]: listening at 0.0.0.0:3333
Thu Mar  7 08:50:24 2019 kern.info ssr-redir[14641]: running from root user
Thu Mar  7 08:50:24 2019 kern.info ssr-local[14904]: initializing ciphers... rc4-md5-6
Thu Mar  7 08:50:24 2019 kern.info ssr-local[14904]: tcp port reuse enabled
Thu Mar  7 08:50:24 2019 kern.info ssr-local[14904]: udprelay enabled
Thu Mar  7 08:50:24 2019 kern.info ssr-local[14904]: udp port reuse enabled
Thu Mar  7 08:50:24 2019 kern.info ssr-local[14904]: listening at 0.0.0.0:23456
Thu Mar  7 08:50:24 2019 kern.info ssr-local[14904]: running from root user
Thu Mar  7 08:50:24 2019 daemon.info dnsmasq[14314]: exiting on receipt of SIGTERM
Thu Mar  7 08:50:25 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Mar  7 08:50:25 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: started, version 2.80 cachesize 10000
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: DNS service limited to local subnets
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth no-DNSSEC loop-detect inotify dumpfile
Thu Mar  7 08:50:25 2019 daemon.warn dnsmasq[14979]: warning: ignoring resolv-file flag because no-resolv is set
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq-dhcp[14979]: DHCP, IP range 192.168.2.100 -- 192.168.2.249, lease time 1h
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using local addresses only for domain test
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using local addresses only for domain onion
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using local addresses only for domain localhost
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using local addresses only for domain local
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using local addresses only for domain invalid
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using local addresses only for domain bind
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain dm5.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain cdndm5.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain manhuaren.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain microsoft.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain apple.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain openwrt.org
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain apnic.net
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain raw.githubusercontent.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain github.io
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain github.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain google.com.ncr
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 127.0.0.1#7913 for domain google.com.tw
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzzyit.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzzyb.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzzsxx.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzzmode.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzzj.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzz4.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzyzphoto.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzyjs.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzyjedu.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzyftrade.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzydb.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzxx.in
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzxw.net
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzxdc.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzx163.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzwqqx.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzwms.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using nameserver 119.29.29.29#53 for domain zzwljc.com
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: using 46647 more nameservers
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: read /etc/hosts - 4 addresses
Thu Mar  7 08:50:25 2019 daemon.info dnsmasq[14979]: read /tmp/hosts/dhcp.cfg01411c - 6 addresses
Thu Mar  7 08:50:31 2019 daemon.warn dnsmasq[14979]: Maximum number of concurrent DNS queries reached (max: 150)
Thu Mar  7 08:50:38 2019 daemon.warn dnsmasq[14979]: Maximum number of concurrent DNS queries reached (max: 150)

**Comment by fw867** [comment]
固件版本呢？

**Comment by hxjs123** [comment]
最新uefi固件版本 这次koolss更新 国外dns选项里好多都不能进程启动。我测试的 cdns dns2socks
当然pdnsd的UDP模式也就不正常。

**Comment by xxb** [comment]
更新到2.2.1后翻不出去了

**Comment by xxb** [comment]
> 更新到2.2.1后翻不出去了

国外DNS那里选择Pcap_DNSProxy才能翻出去，其它选项试了几个都不行。

**Comment by nbagui** [comment]
已经退回到2.20
不光是翻不出去，连正常的国内访问也有问题。打开SS，酷软中心就下线

**Comment by nkcfc** [comment]
原来都遇到这个问题了。dns2sock启动 会出现Segmentation fault。新旧有点区别。旧的是dynamically linked。
root@Openwrt:/koolshare/bin# file /tmp/dns2socks 
/tmp/dns2socks: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, corrupted section header size
root@Openwrt:/koolshare/bin# file dns2socks 
dns2socks: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, corrupted section header size

**Comment by nkcfc** [comment]
我的系统是2.29,系统是2.27也是一样的错误。

**Comment by nkcfc** [comment]
cdns文件也有问题
root@Openwrt:~# /koolshare/bin/cdns 
Error loading shared library libevent-2.1.so.6: No such file or directory (needed by /koolshare/bin/cdns)
Error relocating /koolshare/bin/cdns: event_base_free: symbol not found
Error relocating /koolshare/bin/cdns: event_base_new: symbol not found
Error relocating /koolshare/bin/cdns: evutil_inet_pton: symbol not found
Error relocating /koolshare/bin/cdns: event_base_loopbreak: symbol not found
Error relocating /koolshare/bin/cdns: evutil_sockaddr_cmp: symbol not found
Error relocating /koolshare/bin/cdns: event_new: symbol not found
Error relocating /koolshare/bin/cdns: event_add: symbol not found
Error relocating /koolshare/bin/cdns: event_base_dispatch: symbol not found
Error relocating /koolshare/bin/cdns: evutil_closesocket: symbol not found
Error relocating /koolshare/bin/cdns: event_free: symbol not found
Error relocating /koolshare/bin/cdns: event_del: symbol not found
Error relocating /koolshare/bin/cdns: evutil_parse_sockaddr_port: symbol not found
Error relocating /koolshare/bin/cdns: event_get_fd: symbol not found
Error relocating /koolshare/bin/cdns: evutil_make_socket_nonblocking: symbol not found
Error relocating /koolshare/bin/cdns: event_active: symbol not found
Error relocating /koolshare/bin/cdns: evutil_secure_rng_get_bytes: symbol not found

**Comment by yy915cn** [comment]
离线安装旧版本安装不了啊。。。

**Comment by Jim78778** [comment]
翻车了，测试了2.29/2.27/2.26只要升级ss就翻车

**Comment by hoseahsu** [comment]
翻车了过来的

**Comment by rickychaw** [comment]
看来不是个别现象，不知道什么时候修复，没有官方人出来
