### ISSUE TITLE
（bug反馈）LAN口修改IP段无效

### ISSUE THREAD

**Issue by sunsan05** [koolshare/ledesoft#269]
固件系统版本：2.29（Openwrt Koolshare mod V2.29 r7707-6f685d297b）

内核版本：4.14.103 

硬件系统：J1900 4网口工控机，PAIQ EC3-BT19D4L 

网卡型号：Intel® Ethernet Controller I211 Series

---

现象描述：

重置系统完毕后，LAN口默认为eth0，WAN默认为eth1。

修改LAN口为eth1.2.3，WAN口为eth0。

然后修改LAN口的 静态地址 IP，192.168.1.1 为 192.168.50.1 时，保存成功，但是实际上修改无效。

只有通过修改系统配置文件才可以生效。

**Comment by hxjs123** [comment]
> 固件系统版本：2.29（Openwrt Koolshare mod V2.29 r7707-6f685d297b）
> 
> 内核版本：4.14.103
> 
> 硬件系统：J1900 4网口工控机，PAIQ EC3-BT19D4L
> 
> 网卡型号：Intel® Ethernet Controller I211 Series
> 
> 现象描述：
> 
> 重置系统完毕后，LAN口默认为eth0，WAN默认为eth1。
> 
> 修改LAN口为eth1.2.3，WAN口为eth0。
> 
> 然后修改LAN口的 静态地址 IP，192.168.1.1 为 192.168.50.1 时，保存成功，但是实际上修改无效。
> 
> 只有通过修改系统配置文件才可以生效。

界面就该ip地址需要双重确认的，还是建议配置文件修改，界面修改不方便

**Comment by sunsan05** [comment]
明白了，感谢。
