### ISSUE TITLE
Koolss不要更新2.2.1版本哦，GG了。

### ISSUE THREAD

**Issue by TThwaite** [koolshare/ledesoft#270]
今天手贱更新了，国外连接崩了，然后软件中心也无法联网，我甚至都重装了软路由都无法解决。。。。回退2.2.0版本啥事都没了。。。。希望开发者大大能看看什么问题，能在下个版本修复吧。但是2.2.1版本的DNS选择Pcap_DNSProxy还是可以用，不过强迫症还是希望能够修复一下。

**Comment by TThwaite** [comment]
另外可以增加koolss插件的配置备份功能么

**Comment by aswadmin** [comment]
求怎么回退

**Comment by aswadmin** [comment]
我现在的问题也是这样，只要是更新了马上就出问题

**Comment by yy915cn** [comment]
离线安装2.2.0后，web页面打不开了
报错：
/usr/lib/lua/luci/dispatcher.lua:396: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/util.lua:623: Unable to establish ubus connection
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:396: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by aswadmin** [comment]
这个有什么方法解决吗？重新安装2.20版本吗？
