### ISSUE TITLE
KoolProxy的去广告部分网站不行。

### ISSUE THREAD

**Issue by ilee2go** [koolshare/ledesoft#272]
![qq 20190308155340](https://user-images.githubusercontent.com/11331080/54015408-9a4d7200-41ba-11e9-9364-25e557ce94dd.png)

如图所示，1024点击帖子后，会提示网页元素被过滤器破坏，无法显示内容。
应该是增加了反去广告机制，能不能修复下。

**Comment by dalu-test** [comment]
同样有这个问题
