### ISSUE TITLE
OpenWRT升级到2.30后，腾讯存储云备份无法启动了

### ISSUE THREAD

**Issue by syuraking** [koolshare/ledesoft#273]
已经删除，再重装安装，配置正确，依然是无法启动
提示：备份系统未运行

**Comment by rickychaw** [comment]
> 已经删除，再重装安装，配置正确，依然是无法启动
> 提示：备份系统未运行

确实有这个问题

**Comment by syuraking** [comment]
root@Tsubasa:/koolshare/scripts# ./cos_config.sh start
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /koolshare/bin/cos)
Error relocating /koolshare/bin/cos: CRYPTO_set_locking_callback: symbol not found
Error relocating /koolshare/bin/cos: ERR_free_strings: symbol not found
Error relocating /koolshare/bin/cos: CRYPTO_num_locks: symbol not found
Error relocating /koolshare/bin/cos: EVP_MD_CTX_destroy: symbol not found
Error relocating /koolshare/bin/cos: ERR_load_crypto_strings: symbol not found
Error relocating /koolshare/bin/cos: CRYPTO_set_id_callback: symbol not found
Error relocating /koolshare/bin/cos: CRYPTO_set_dynlock_destroy_callback: symbol not found
Error relocating /koolshare/bin/cos: CRYPTO_set_dynlock_lock_callback: symbol not found
Error relocating /koolshare/bin/cos: OPENSSL_add_all_algorithms_noconf: symbol not found
Error relocating /koolshare/bin/cos: CRYPTO_cleanup_all_ex_data: symbol not found
Error relocating /koolshare/bin/cos: EVP_MD_CTX_create: symbol not found
Error relocating /koolshare/bin/cos: EVP_cleanup: symbol not found
Error relocating /koolshare/bin/cos: CRYPTO_set_dynlock_create_callback: symbol not found
{"result":-1}

错误记录，好像是少了组件？

**Comment by syuraking** [comment]
发现已经修复，感谢！
