### ISSUE TITLE
v2ray更改本地端口和传入协议

### ISSUE THREAD

**Issue by google9002** [koolshare/ledesoft#276]
我用ssh查看了一下，软件中心里面的v2ray默认使用dokodemo-door这个传入协议，且本地地址为1280
我尝试在v2ray.json里面直接修改传入协议和本地端口，但是在系统重启后会自动变回原样

我现在遇到的问题是，一方面lede这个v2ray似乎不太稳定，无论选择哪个模式，都有可能突然翻不了墙了，比如1min之前google还是能用的，但是youtube不行，现在是youtube能用，谷歌不行了。。。另一方面，我希望能用switchyomega管理哪些网站翻墙哪些不翻，但是switchyomega仅支持socks协议

确认不是我的代理服务器的问题，因为我手机上是同一个节点，毫无问题

**Comment by Transparent0** [comment]
Google  YouTube 间歇性打不开，考虑下是不是ipv6 的问题，我之前也是时不时抽风，后来发现是因为有时候是通过ipv6 访问了。把ipv6 关闭后，再也没有出过类似问题。
switchyomega 代理这个，同求。。。。

**Comment by google9002** [comment]
@Transparent0 google和youtube的问题，我现在解决了，是启用了json当中的routing项，顺便解决了下谷歌商店的问题
现在只求switchyomega了。。。

**Comment by HXinD** [comment]
+1。。希望 除了dokodemo-door以外 还能留个socks或者http的inbound。dokodemo-door的确有照顾不到的地方。

**Comment by xuanzai89757** [comment]
小白弄了半天原来没端口....switchyomega刚需+1

**Comment by fw867** [comment]
已更新
