### ISSUE TITLE
[功能请求] v2ray插件建议增加节点状态检测功能

### ISSUE THREAD

**Issue by huxim** [koolshare/ledesoft#278]
v2ray需要个检测节点状态功能,现在的随机切换经常切换到失效的节点上去,不需要太高级的检测,定时ping一下就行
![image](https://user-images.githubusercontent.com/2505801/54106898-9025b080-4412-11e9-9ef4-be43299593b1.png)

**Comment by fw867** [comment]
icmp也不是特别靠谱的测试方案，所以节点不在多，一个稳定就行了
