### ISSUE TITLE
ss大陆白名单模式指定端口访问无效

### ISSUE THREAD

**Issue by eeoa** [koolshare/ledesoft#279]
koollede版本2.29，koolss版本2.2.2，指定只通过80和443，我在远程构建了一个其他端口的nginx来查看本地ip，结果返回的还是ss节点的ip。

**Comment by jerryhan2018** [comment]
国外模式（大陆白名单）好像就是这样，我的困惑是GFWlist用不了，用这个模式跟没开ss一样，只能用国外模式，但IP就一直是代理的IP，并且Bing也访问不了(放域名白名单都不行)

版本跟你一样，重装过ss也不行，苦闷死了5555555

**Comment by ffllc** [comment]
各位大神,请问gfwlist不能访问google.com,但是大陆白名单可以,要怎么办.
在黑名单中添加 google.com无效
