### ISSUE TITLE
V2RAY配置文件通过，但固件版本过低

### ISSUE THREAD

**Issue by uling117** [koolshare/ledesoft#281]
![新建位图图像](https://user-images.githubusercontent.com/28148333/54251003-d4cf5a00-4580-11e9-953f-fc388b7ff6ad.jpg)

**Comment by uling117** [comment]
求教各位大神，如何解决

**Comment by FengkuiChan** [comment]
升级openwrt版本

**Comment by pastay** [comment]
我也有相同的问题，openwrt版本Openwrt Koolshare mod V2.30 r10402-51ad900e2c

**Comment by yellowvii** [comment]
这里应该是 v2ray 官方的 json 里面会带 // 注释，但是标准的 json 是不支持的，所以 v2ray 检查配置正确，但是路由器插件提示不支持，去除配置 json 里面所有的 // 注释再试
