### ISSUE TITLE
第一次刷LEDE，装了V2RAY ，出现V2Ray配置文件没有通过测试，请检查设置，请大神看看

### ISSUE THREAD

**Issue by kingda2005** [koolshare/ledesoft#284]
【2019年03月16日 09:08:14】: ---------------------- LEDE 固件 v2ray -----------------------
【2019年03月16日 09:08:14】: v2ray符合启动条件！~
【2019年03月16日 09:08:14】: 重启dnsmasq服务...
【2019年03月16日 09:08:17】: 尝试先清除已存在的iptables规则，防止重复添加
【2019年03月16日 09:08:18】: 先清空已存在的ipset名单，防止重复添加
【2019年03月16日 09:08:18】: 清除重复的ip rule规则.
【2019年03月16日 09:08:18】: 删除ip route规则.
【2019年03月16日 09:08:18】: 清除firewall中相关的 v2ray 启动命令...
【2019年03月16日 09:08:18】: 创建国内CDN解析优化配置文件
【2019年03月16日 09:08:18】: 创建国外GFW解析优化配置文件
【2019年03月16日 09:08:18】: 创建状态检测解析优化配置文件
【2019年03月16日 09:08:18】: DNS解析方案国外优先，优先解析国外DNS.
【2019年03月16日 09:08:18】: 添加nat-start触发事件...
【2019年03月16日 09:08:18】: 优化网络参数
【2019年03月16日 09:08:18】: 使用 12 配置文件...
【2019年03月16日 09:08:18】: 解析V2Ray配置文件...
【2019年03月16日 09:08:18】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2019年03月16日 09:08:18】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
【2019年03月16日 09:08:18】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
【2019年03月16日 09:08:18】: 测试V2Ray配置文件.....
【2019年03月16日 09:08:18】: V2Ray配置文件没有通过测试，请检查设置!!!
【2019年03月16日 09:08:18】: 出错原因：main: failed to read config file: /tmp/v2ray_tmp.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 1 > invalid character 'v' looking for beginning of value > exit status 255
【2019年03月16日 09:08:18】: 插件将在5秒后自动关闭！！
【2019年03月16日 09:08:19】: 5
【2019年03月16日 09:08:20】: 4
【2019年03月16日 09:08:21】: 3
【2019年03月16日 09:08:22】: 2
【2019年03月16日 09:08:23】: 1
【2019年03月16日 09:08:24】: 0
【2019年03月16日 09:08:29】: 某些老版本固件已经无法使用新版插件，请升级到最新版固件使用！
【2019年03月16日 09:08:29】: 插件已关闭！！
【2019年03月16日 09:08:29】: ------------------------- v2ray 成功关闭 -------------------------

**Comment by potterlee0574** [comment]
请问你是怎么解决的啊？我跟你一样的情况
