### ISSUE TITLE
老问题，cdns进程出错

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#285]
固件版本：V2.30 r10402-51ad900e2c
插件版本：koolss for OpenWRT/LEDE 2.2.2
出错信息：
[ 4208.802296] cdns[11092]: segfault at 7ffd76ff1013 ip 0000000000406f3b sp 00007ffd76fc1598 error 4 in cdns[403000+8000]
[93226.259902] cdns[46193]: segfault at 7ffdc254a013 ip 0000000000406f3b sp 00007ffdc251a3a8 error 4 in cdns[403000+8000]
[122340.014723] cdns[5768]: segfault at 7ffd951cd013 ip 0000000000406f3b sp 00007ffd9519e028 error 4 in cdns[403000+8000]

cdns.json信息：`{
	"global": {
		"daemon": true,
		"log": "syslog:daemon",
		"pidfile": "/var/run/cdns.pid",
		"log_debug": false
	},
	"cdns": {
		"listen_ip": "127.0.0.1",
		"listen_port": 7913,
		"timeout": 2,
		"servers": [
			{
				"ip_port": "1.1.1.1"
			},
			{
				"ip_port": "208.67.222.222"
			},
			{
				"ip_port": "8.8.8.8"
			},
			{
				"ip_port": "9.9.9.9"
			},
			{
				"ip_port": "80.80.80.80"
			}
		]
	}
}`

烦请大佬们看看，这个cdns挺好用的，就是有时候进程出错了，说实话不想放弃掉。

**Comment by fw867** [comment]
删除插件重新安装

**Comment by hxjs123** [comment]
重装插件和重刷固件，俩种不保留数据回炉都试过了，还是会不定期出错
