### ISSUE TITLE
可能lede 2.9 致ss 1.98 出口设定问题 及游戏模式udp转发不通

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#29]
RT，部分日志如下：
【2017年11月24日 15:34:00】: 创建域名黑/白名单软链接到/tmp/dnsmasq.d/wblist.conf
【2017年11月24日 15:34:00】: 创建cdn加速列表软链接/tmp/dnsmasq.d/cdn.conf
【2017年11月24日 15:34:00】: 创建gfwlist的软连接到/tmp/dnsmasq.d/文件夹.
【2017年11月24日 15:34:00】: DNS解析方案国外优先，优先解析国外DNS.
**_【2017年11月24日 15:34:00】: 【出口设定】设置 116.228.111.18 出口为 pppoe-wan 【】失败, 因为pppoe-wan 【】已经离线!!! 116.228.111.18将会自动选择出口！
【2017年11月24日 15:34:00】: 【出口设定】设置 180.168.255.118 出口为 pppoe-wan 【】失败, 因为pppoe-wan 【】已经离线!!! 180.168.255.118将会自动选择出口！_**
【2017年11月24日 15:34:00】: 添加nat-start触发事件...
【2017年11月24日 15:34:00】: 加入开机自动启动...
【2017年11月24日 15:34:00】: 关闭SS规则自动更新.
【2017年11月24日 15:34:00】: 开启ssr-redir进程，用于透明代理.
【2017年11月24日 15:34:00】: 加载nat规则!

现未发现影响使用（除了udp应用无法使用），望新版本顺带修复下

**Comment by XenMe** [comment]
我这边也碰到了，单臂模式，没有WAN口，导致无法获取WAN，保存设置后，在负载均衡列表无法看到目前添加的server，点其他设置提交保存很大概率丢失之前添加的负载均衡服务器。

设置好不去乱动的话，如主楼反应，不影响使用。
