### ISSUE TITLE
DDNS cloudflare ipv6和ipv4 相同子域名的时候互相覆盖问题

### ISSUE THREAD

**Issue by kakotor** [koolshare/ledesoft#290]
DDNS 配置了ipv4和ipv6的解析
但是最终解析结果只会保留一个
脚本内应该是未严格区分更新的域名是AAAA记录还是A记录

**Comment by fw867** [comment]
是拿ZONEID的时没有区分A还是AAAA,可能是我在看API的时候漏掉了，下次有空更新一下，建议分开不同的域名吧
