### ISSUE TITLE
软件中心 离线安装会导致http服务凉凉

### ISSUE THREAD

**Issue by vivuvv** [koolshare/ledesoft#296]
上传离线包后导致http服务凉凉

**Comment by houzi-** [comment]
哪个插件安装会导致这样的问题？

**Comment by vivuvv** [comment]
复现方法：https://github.com/koolshare/ledesoft/blob/ledetest/homebridge/history/0.5/homebridge.tar.gz 这个下载两次 在windows下 第二个文件会被重命名为homebridge（2）.tar.gz 然后将此文件上传上去，会导致httped服务崩溃

**Comment by vivuvv** [comment]
顺便问问，最新版本的homebridge好像有问题，一直提示 小米智能家居硬件支持-1安装失败，你的网络可能有问题，请重试！ 求公开 https://github.com/koolshare/ledesoft/tree/master/homebridge/homebridge/scripts的源代码，以便于排查问题

**Comment by houzi-** [comment]
好的！我们会解决进行测试解决这个问题的
