### ISSUE TITLE
LEDE配置v2ray无法通过测试，请大佬帮忙看一下

### ISSUE THREAD

**Issue by potterlee0574** [koolshare/ledesoft#305]
【2019年04月03日 11:48:20】: ---------------------- LEDE 固件 v2ray -----------------------
【2019年04月03日 11:48:20】: v2ray符合启动条件！~
【2019年04月03日 11:48:20】: 重启dnsmasq服务...
【2019年04月03日 11:48:24】: 尝试先清除已存在的iptables规则，防止重复添加
【2019年04月03日 11:48:25】: 先清空已存在的ipset名单，防止重复添加
【2019年04月03日 11:48:25】: 清除重复的ip rule规则.
【2019年04月03日 11:48:25】: 删除ip route规则.
【2019年04月03日 11:48:25】: 清除firewall中相关的 v2ray 启动命令...
【2019年04月03日 11:48:25】: 创建国内CDN解析优化配置文件
【2019年04月03日 11:48:25】: 创建国外GFW解析优化配置文件
【2019年04月03日 11:48:25】: 创建状态检测解析优化配置文件
【2019年04月03日 11:48:25】: DNS解析方案国外优先，优先解析国外DNS.
【2019年04月03日 11:48:25】: 添加nat-start触发事件...
【2019年04月03日 11:48:25】: 优化网络参数
【2019年04月03日 11:48:25】: 使用 配置文件...
【2019年04月03日 11:48:25】: 解析V2Ray配置文件...
【2019年04月03日 11:48:25】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2019年04月03日 11:48:26】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
【2019年04月03日 11:48:26】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
【2019年04月03日 11:48:26】: 测试V2Ray配置文件.....
【2019年04月03日 11:48:26】: V2Ray配置文件没有通过测试，请检查设置!!!
【2019年04月03日 11:48:26】: 出错原因：main: failed to read config file: /tmp/v2ray_tmp.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 88 > invalid character ',' looking for beginning of value > exit status 255
【2019年04月03日 11:48:26】: 插件将在5秒后自动关闭！！
【2019年04月03日 11:48:27】: 5
【2019年04月03日 11:48:28】: 4
【2019年04月03日 11:48:29】: 3
【2019年04月03日 11:48:30】: 2
【2019年04月03日 11:48:31】: 1
【2019年04月03日 11:48:32】: 0
【2019年04月03日 11:48:36】: 某些老版本固件已经无法使用新版插件，请升级到最新版固件使用！
【2019年04月03日 11:48:36】: 插件已关闭！！
【2019年04月03日 11:48:36】: ------------------------- v2ray 成功关闭 -------------------------

**Comment by fw867** [comment]
failed to read config file at line 1 char 88 > invalid character ',' looking for beginning of value 
日志都已经给出原因了，明显你配置文件有问题！

**Comment by potterlee0574** [comment]
本来就用233脚本傻瓜式搭建的，电脑、手机、梅林上都能用，真不知道配置文件哪里有问题

**Comment by Nicepaul** [comment]
vmess url是不是中间有空格？把空格删了重新添加节点就可以了

**Comment by potterlee0574** [comment]
> vmess url是不是中间有空格？把空格删了重新添加节点就可以了

谢谢！可以了！
