### ISSUE TITLE
软件中心报错“连接丢失”

### ISSUE THREAD

**Issue by gcell** [koolshare/ledesoft#31]
版本信息：服务器：LEDESoft 当前版本：0.3.1 , 线上版本：0.3.1  
lede 2.8更新到2.10后，进入软件中心点击任意已安装插件即报错“连接丢失，正在重新连接”。
随后30秒左右出现500错误页面。
![qq 20171128172238](https://user-images.githubusercontent.com/234187/33311949-566f3ffe-d461-11e7-893f-6dbc44949946.png)
![qq 20171128172312](https://user-images.githubusercontent.com/234187/33311948-5635d232-d461-11e7-8ece-d04fe6cf646f.png)

**Comment by gcell** [comment]
试了下，有点新发现，插件更新的按钮可用时，点击更新，之后的插件可以正常点开不会报错

**Comment by gcell** [comment]
2.10升级2.11继续存在这个问题

**Comment by gcell** [comment]
暂时解决办法 https://github.com/koolshare/ledesoft 到这里进入各个插件的目录，下载其中的压缩文件，逐个到离线安装页面安装，可以修复

**Comment by rickycm** [comment]
我也遇到这个问题，试试手动重装的方法再来回复

**Comment by ibule** [comment]
同样错误 lede真垃圾
