### ISSUE TITLE
v2ray for openwrt - 2.3.6 增加用户提示

### ISSUE THREAD

**Issue by yellowvii** [koolshare/ledesoft#311]
希望在插件填写 v2ray 配置 json 的时候说明，**需要完全去除 json 中的 // 注释**

因为 V2Ray 官方提供的配置 Json 都是携带 // 注释的，但是标准 Json 并不支持这种格式。

如果填写了带注释的 json，查看 log 会提示 ”V2RAY配置文件通过，但固件版本过低“，而且 log 中会提示 v2ray 配置文件 “测试V2Ray配置文件.....” “Configuration OK.” ，非常有迷惑性。

**Comment by tzigone** [comment]
用脚本自动生成的不会有 // 这类注释 ，这种过滤没必要。 一般都是网上的案例代码引起的。

**Comment by yellowvii** [comment]
> 用脚本自动生成的不会有 // 这类注释 ，这种过滤没必要。 一般都是网上的案例代码引起的。

不需要插件过滤 // 注释，只需要在插件上的 UI 界面提现需要清除 // 注释即可，因为 v2ray 官方的模板配置文件就有注释。而且带“注释”的配置文件导致的出错信息很有歧义，导致我当时排查时绕了好大一个弯。

其实只需要插件网页上一行粗体字说明就能帮助很多人
