### ISSUE TITLE
V2ray能连接服务器但是ping不通外网

### ISSUE THREAD

**Issue by ZhaiCanZC** [koolshare/ledesoft#317]
同样的服务器，同样的配置，电脑和手机都没有问题，但是用插件的话就ping不通，外网网页也打不开

**Comment by ZhaiCanZC** [comment]
我感觉虽然连接上了服务器，但是插件似乎并没有走代理，无论我选择什么代理模式，我在服务端那边的log里都没看到有什么动静，只有插件自动检测的请求有收到，其他的请求都没有

**Comment by mottzz** [comment]
一样的情况，请问找到解决方法了吗
