### ISSUE TITLE
v2ray 插件功能请求

### ISSUE THREAD

**Issue by lzghzr** [koolshare/ledesoft#323]
因为目前插件不支持自定义inbound，而且sh脚本闭源，所以希望可以在inbound加入tag用以区分流量来源，比如
socks5，1281端口使用`"tag": "socks5"`
http，1282端口使用`"tag": "http"`
配合routing可以实现一些高级功能

**Comment by lzghzr** [comment]
由于自定义文件过大，尝试手动更改 `/tmp/v2ray_tmp.json` 重启服务会被覆盖掉，希望可以提供大文件支持或者自定义json等高级功能

**Comment by fw867** [comment]
已经更新
