### ISSUE TITLE
老问题，暂未修复，ss插件版本号1.9.9.6

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#35]
目前我所知的： pdnsd udp ss-tunnel 自定义失常，功能可能正常，显示失常
cdns dns2socks 自定义失常， 显示正常，功能失常

> 【2017年12月08日 22:32:06】: ┏ 你选择了chinaDNS作为解析方案！
【2017年12月08日 22:32:06】: ┣ 开启ss-local,为dns2socks提供socks5端口：23456
【2017年12月08日 22:32:06】: ┣ 开启dns2socks，作为chinaDNS上游国外dns，转发dns：
【2017年12月08日 22:32:06】: ┗ 开启chinadns进程！

![image](https://user-images.githubusercontent.com/31793080/33770252-e20e952e-dc67-11e7-8a2b-549e67206bfe.png)

**Comment by sadoneli** [comment]
fixed in 1.9.9.7
