### ISSUE TITLE
KoolProxy 3.6.3 WAN口80防火墙规则失效

### ISSUE THREAD

**Issue by naoki66** [koolshare/ledesoft#38]
KoolProxy 3.6.3全局模式，WAN口80端口自己引导到了LEDE的登陆界面。
设置80端口拒绝或者转发到内网的某个机器也不行。
公网极其危险，也导致WEB应用失效。

**Comment by naoki66** [comment]
ipset模式无此问题

**Comment by houzi-** [comment]
应该是你的iptables问题
