### ISSUE TITLE
建议所有插件界面加入高级选项“自定义参数”

### ISSUE THREAD

**Issue by gzsdbb** [koolshare/ledesoft#4]
现在软件中心的插件虽然变得简单易用，但是设置方面还是短板，如aria2 本来可以设置的参数是相当多的（如on-download-complete=），可是只能软件中心中界面只能设置几项而已，完全发挥不出原来的强大功能。当然这个不只单单aria2，vsftp等等插件也同理。
    虽然使用者也可以自行到安装目录下去一个个修改插件相应的设置文件，但这明显变得不高效与不方便。以及插件更新后还要继续修改！（现时aria2的插件配置文件在每次启动aria2的时候都会重置，所以修改也变得麻烦只能到启动文件中aria2_run.sh用sed -i 加入某些参数项到aria2.conf文件中）
   如果要把所有设置都加入到界面中，那明显是不明智的，因为参数太多了，所以只加入一项自定义参数，还是能满足有需要的人群使用，这样就可以自定义加入一个或多个设置参数。

**Comment by fw867** [comment]
软件中心的目的是为了方便一些基础用户，降低使用门槛，达到上手可用的目的，过多的配置项会让他们很困惑。对于有能力的高级用户完全可以自己来解决一些问题，但我们会考虑你的建议。
