### ISSUE TITLE
2.12固件下koolss失效，

### ISSUE THREAD

**Issue by SoukinOKATU** [koolshare/ledesoft#42]
DNSproxy模式国内国外一律为X，DNS2socks模式下国外X 国内正常，但上网依然不正常
重新安装koolss无效，固件回滚至2.10后koolss恢复正常

**Comment by sicode** [comment]
跟你差不多，刚刚装好2.12的时候还是正常，前天突然间就不行了

**Comment by sunqqq1987** [comment]
我今天装也是不行，服务器用电脑直接连是没问题的，国外显示x，不知道是不是dns问题

**Comment by spellyaohui** [comment]
能给一下2.12的下载地址吗?官方的找不到了~
