### ISSUE TITLE
zerotier1.2.4-3

### ISSUE THREAD

**Issue by leviacn** [koolshare/ledesoft#48]
2018年01月29日 16:39:04 开始运行主服务
2018年01月29日 16:39:04 Done!
2018年01月29日 16:39:04 开始配置网络接口ZEROTIER
2018年01月29日 16:39:04 Done!
2018年01月29日 16:39:04 开始配置防火墙
2018年01月29日 16:39:04 Done!
2018年01月29日 16:39:04 开始配置ID
2018年01月29日 16:39:04 等待建立连接15s
/usr/bin/zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
2018年01月29日 16:39:19 Done!
2018年01月29日 16:39:19 ============================================
2018年01月29日 16:39:19 all done enjoy！

我在软路由上使用的时候，旧版本的zerotier1.2.4-2没有问题，1.2.4-3则少了上面那个zerotier-one文件夹。

**Comment by leviacn** [comment]
LEDE X64 V2.14 ，我记得1.2.4-2在版本V2.11那版的软件中心上面，求一个Zerotier1.2.4-2

**Comment by leviacn** [comment]
应该是没有有效运行一次"gengerate"去生成这个文件夹。

**Comment by leviacn** [comment]
原本以为需要zerotier1.2.4-2配合以免运行 Zerotier的时候返回 401 join 的问题。
综上，如果提示缺少/var/lib/zerotier-one里的文件，这个文件夹要配置/etc/config/Zerotier配置文件，Zerotier 根服务器看到配置文件里有gengerate会给你一些参数以生成客户端文件，初始化运行zerotier后会生成/var/lib/zerotier-one文件夹及文件。

一般性的访问局域网其它机器需要在 firewall.user里面加入下面两句
iptables -A FORWARD -d 192.168.100.0/24 -j ACCEPT
iptables -A FORWARD -s 192.168.100.0/24 -j ACCEPT 
这样基本就可以访问一般的机器。

但局域网里的其它机器如做旁路的小米路由器的一些特殊的机器，还需要加入以下一句，不然会返回错误信息
iptables -t nat -A POSTROUTING -j MASQUERADE
可以访问，不过Zerotier启动的时候会返回401 join的信息。

只需要再限定一下就可以了，这样加没问题。
iptables -t nat -A POSTROUTING -d 192.168.100.0/24 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -j MASQUERADE

启动Zerotier，返回 200 join.

**Comment by sevenfxx** [comment]
@leviacn 你好，我安装这个插件是也是提示这个错误，请问要具体怎么操作解决？输入什么命令，谢谢。

**Comment by leviacn** [comment]
@sevenfxx 后来发现只需要把 /etc/config/zerotier 这个配置文件改成

config zerotier 'default'
	option enabled '1'
	option interface 'wan'
	option port '9993'
	list join '这里填你的Network ID'
	option secret 'generate'

然后，正常的到插件中心路那里 启动运行Zerotier就可以了。

**Comment by leviacn** [comment]
直接service zerotier start也可以

**Comment by sevenfxx** [comment]
@leviacn 多谢
