### ISSUE TITLE
koolproxy 跟 不可名状之物 冲突

### ISSUE THREAD

**Issue by Coolkids** [koolshare/ledesoft#5]
开了koolproxy后 不可名状之物 
接管局域网DNS解析 失效
黑名单IP模式  失效
访问控制 失效

**Comment by monokoo** [comment]
你kp是什么模式，ss是什么模式呀

**Comment by sadoneli** [comment]
koolproxy和koolss的冲突，目前用以下两种方式解决（二选一）：
1 更改lan ip地址为192.168.1.1
2 关闭mwan（进入负载均衡关闭）

**Comment by Coolkids** [comment]
嗯 关闭mwan后好了 多谢

**Comment by chylli** [comment]
仍然冲突 ac86u  请问 @sadoneli mwan是啥？我在负载均衡那里没看到这个
