### ISSUE TITLE
SSRServer有时自动停止，无法科学上网。

### ISSUE THREAD

**Issue by ygfly** [koolshare/ledesoft#51]
这个真的能利用路由的来科学上网吗？“科学上网”是否选中都是一样的，连接这个的设备都无法科学上网，难道是免流专用？然而现在流量很便宜了。

**Comment by andyhuai** [comment]
我也是，勾选了客户端代理，也不会科学上网，而且server有时候还自动挂了，就连不上了，之前Merlin版的可用，感觉无法和KOOLSS配合
