### ISSUE TITLE
koolss插件 节点管理内自定义混淆参数输入框有字符限制

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#53]
问题如题所述，混淆参数比如我填入的一下参数：yahoo.com,timway.com,yam.com,naver.com,yandex.com,excite.com,oscobo.co.uk,fireball.de,aliyun.com#User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36\nAccept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\nConnection: keep-alive
提示名称无效

**Comment by 24332994** [comment]
好久没更新了
