### ISSUE TITLE
Brook插件无法使用

### ISSUE THREAD

**Issue by qiu18** [koolshare/ledesoft#59]
软件中心下载的Brook插件安装好后无法使用：填写了资料后，无论是哪种brook 代理模式，外网始终是打叉，无法使用。（服务器资料坑定没问题，我用手机和电脑版的可以正常使用）
ssh链接手动运行：./koolshare/scripts/brook_config.sh
输出：
【2018年03月16日 12:36:42】: brook符合启动条件！~
【2018年03月16日 12:36:42】: 删除 brook 相关的名单配置文件.
【2018年03月16日 12:36:42】: 关闭 brook 进程...
【2018年03月16日 12:36:42】: 关闭 redsocks2 进程...
【2018年03月16日 12:36:42】: 加载nat规则!
【2018年03月16日 12:36:42】: 尝试先清除已存在的iptables规则，防止重复添加
【2018年03月16日 12:36:43】: 先清空已存在的ipset名单，防止重复添加
【2018年03月16日 12:36:43】: 清除重复的ip rule规则.
【2018年03月16日 12:36:43】: 删除ip route规则.
【2018年03月16日 12:36:43】: 创建ipset名单
cat: can't open '/etc/config/pppoe': No such file or directory
【2018年03月16日 12:36:43】: 写入iptables规则到nat表中...
iptables v1.6.1: Set gfwlist doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.1: Couldn't load match `geoip':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: File exists
iptables v1.6.1: Couldn't load match `geoip':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
【2018年03月16日 12:36:43】: 加载ACL规则：所有模式为：gfwlist模式
【2018年03月16日 12:36:43】: 开启chromecast功能（DNS劫持功能）
【2018年03月16日 12:36:43】: 开启 brook 主进程...
【2018年03月16日 12:36:43】: 开启 redsocks2 主进程...
【2018年03月16日 12:36:43】: 开启 dnsforwarder 主进程...
【2018年03月16日 12:36:43】: 创建国内CDN解析优化配置文件
【2018年03月16日 12:36:43】: 创建国外GFW解析优化配置文件
【2018年03月16日 12:36:44】: 创建状态检测解析优化配置文件
【2018年03月16日 12:36:44】: DNS解析方案国外优先，优先解析国外DNS.
【2018年03月16日 12:36:44】: 重启dnsmasq服务...
这正常吗？

**Comment by Portan** [comment]
建议你卸载重装下这个插件然后试试
