### ISSUE TITLE
v2ray插件不支持tls+websocket?

### ISSUE THREAD

**Issue by bilijinshi** [koolshare/ledesoft#62]
找不到配置path的位置？

**Comment by Portan** [comment]
使用自定义配置文件(注意服务器地址是IP，不是域名)
{
"log": {
  "loglevel": "warning"
},  
"inbound": {
  "protocol": "dokodemo-door",
  "port": 7913,
  "settings": {
    "address": "8.8.8.8",
    "port": 53,
    "network": "udp",
    "timeout": 0,
    "followRedirect": false
  }
},
"inboundDetour": [
  {
    "domainOverride": ["tls","http"],
    "port": 1280,
    "protocol": "dokodemo-door",
    "settings": {
      "network": "tcp,udp",
      "followRedirect": true
    }
  }
],
  "outbound": {
    "protocol": "vmess",
    "mux":{
      "enabled":true,
      "concurrency":8
    },
    "settings": {
      "vnext": [
        {
          "address": "domain ip........",
          "port": 443,
          "users": [
            {
              "id": "id.........",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "domain name........"
      },
      "wsSettings": {
        "path": "/path........"
      }
    }
  }
}

主要是inbound和inboundDetour,其他的可以用你自己的配置

**Comment by bilijinshi** [comment]
为啥必须要ip？
用ip就没法用cdn隐藏ip了

**Comment by bilijinshi** [comment]
倒不是隐藏，因为有被block的小鸡，通过cdn苟延残喘ing

**Comment by Portan** [comment]
@bilijinshi 电报群里有人提供方法了，把域名写进白名单，自定义配置就能用域名了

**Comment by minitru1014** [comment]
@Portan 老哥能告知下具体的方法么。我也是不能ws+tls的配置
