### ISSUE TITLE
“酷软”出错了，所有的插件都无法获取状态

### ISSUE THREAD

**Issue by cjameslynn** [koolshare/ledesoft#73]
“酷软”里面的所有的插件都无法获取状态
SS和策略路由无法获取wan口信息
更新固件无法获取本机固件信息和最新固件信息
其他插件均无法获取运行状态信息

**Comment by sadoneli** [comment]
请勿安装插件中心内的 家庭云插件，安装这个插件会导致这个问题
你可以尝试以下解决办法
opkg remove curl
如果不行，请重刷固件

这个插件我们将先行进行下架处理，直到作者解决问题

**Comment by cjameslynn** [comment]
删除curl没有用，只能firstboot了
