### ISSUE TITLE
建议X64 LEDE软件商店里的V2RAY更新tls+ws方式

### ISSUE THREAD

**Issue by ntgeralt** [koolshare/ledesoft#79]
感谢作者的分享，稍微建议下：服务端为tls+ws的话，客户端"wsSettings"需要  "path"和 "Host":

**Comment by sadoneli** [comment]
请用json配置

**Comment by ntgeralt** [comment]
我把电脑客户端v2rayn.exe的json文本拷贝进去（打开youtube没问题的），那个小提示 本地端口改为1280，是改"inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
里面1080改为1280吗，我改了后，启动，发现无法打开google 那些，红色小交叉~
