### ISSUE TITLE
koolss 2.07 in 2.17 小毛小病汇总讨论

### ISSUE THREAD

**Issue by hxjs123** [koolshare/ledesoft#81]
koolss的访问控制下拉选择列表框，无内网设备选项，求修复
![qq 20180503164447](https://user-images.githubusercontent.com/31793080/39567353-59e05028-4ef1-11e8-9f88-1fd7dda51b96.png)

临时办法：在web提交后，再次手动重启防火墙之后，能完整显示访问控制下拉选择列表框。

同时，查看过其他插件该项功能：
kp有此问题

**Comment by kingyan** [comment]
表示我这边然而并没有这个问题，正常的。

**Comment by hxjs123** [comment]
确定下版本，217+hwnat么，刚升级的时候我也还行，今天发现不行了。

**Comment by hxjs123** [comment]
好像升级217之后，koolss有点小问题，还发现一例问题，防火墙重启触发koolss重提交，在国外dns使用ss-tunnel会出问题
![qq 20180503181058](https://user-images.githubusercontent.com/31793080/39571273-8c800846-4efd-11e8-833c-3b959aa1d6fd.png)

**Comment by syuraking** [comment]
我这边的问题从2.05更改DNS策略后就出现很奇怪的情况，测试了这长时间，也提下反馈吧。

只有cdns没有任何问题，稳定工作。
其它的模式，都会随机性的无法解析地址，进程上看还是报告在运行，
重启DNS，又能正常工作，再过随机一段时间后，又坏了，日志上也看不出来问题
路由器本身也无法解析国外，一个X。但是手工逆回2.04，一切正常了。

目前还有一个能正常使用的，这里也提出，看看有没有可能去查一下，谢谢。

**Comment by hxjs123** [comment]
多wan设定的选择框，也是时常空白0选择

**Comment by hxjs123** [comment]
追加：正常重启路由器后，dns解析国内外全pd，需要重新提交即可

可疑启动日志节选

> Fri May  4 17:08:44 2018 daemon.info dnsmasq-dhcp[9182]: read /etc/ethers - 0 addresses
Fri May  4 17:08:45 2018 kern.err ssr-tunnel[7736]: getaddrinfo: Try again
Fri May  4 17:08:45 2018 kern.err ssr-tunnel[7736]: failed to resolve the provided hostname
Fri May  4 17:08:48 2018 kern.err ssr-tunnel[9005]: failed to resolve server name, wait 2 seconds

**Comment by hxjs123** [comment]
@kingyan 我最近才发现这个列表空白问题的起因，应该是浏览器问题，最新stable的Chrome版本 66.0.3359.181和Firefox版本60.0.1能重现，我用edge打开列表是无问题的
