### ISSUE TITLE
PPPoE拨号之后koolss重启失败

### ISSUE THREAD

**Issue by w0330t** [koolshare/ledesoft#82]
电信的PPPOE会不定时踢掉用户重新拨号
这时SS服务重启，然后出现国内链接正常，国外链接一把叉
我咨询并测试了一下，找了另外一个SSR的配置重拨之后正常
出问题的SS Server配置加密方式为aes-128-gcm并且强制使用http混淆，多个服务器节点均有该问题。
服务器均由个人自行配置，其他操作系统均无任何问题。
如果需要的话请留下联系方式以便我把节点配置发送给你们做调试
最终的测试是使用原版ss然后使用obfs的http混淆均会出现这个问题。然后吐槽为啥现在都喜欢用R

**Comment by KimiChen** [comment]
防火墙重启触发koolss重启！

我是时不时的防火墙触发导致 国外链接正常 国内链接一把叉
