### ISSUE TITLE
当没有wan口(单网卡)，koolss多WAN出口选择异常

### ISSUE THREAD

**Issue by XenMe** [koolshare/ledesoft#87]
Uncaught TypeError: Cannot read property 'wans' of null
<img width="422" alt="ss_getwans" src="https://user-images.githubusercontent.com/2133231/39756370-e56d5de4-52fb-11e8-9354-d279d98098a8.png">
ss_getwans.sh返回空，导致wans为null, wans.sort()抛出异常
目前是
替换wans = wans.sort() 为
if(wans==null) wans=[]; else wans = wans.sort()
解决这个显示问题

修复后结果如下：
<img width="306" alt="fixed" src="https://user-images.githubusercontent.com/2133231/39756523-92d0068a-52fc-11e8-8ff2-627843d81944.png">

**Comment by fonlan** [comment]
希望能尽快合入，这个改动太重要了，否则在LEDE作为旁路网关的时候koolss的负载均衡完全用不了
