### ISSUE TITLE
SSRServer 大佬们帮帮忙

### ISSUE THREAD

**Issue by iam3ddy** [koolshare/ledesoft#90]
新买的软路由
lede v2.15，只设置了WAN。
可是ssrserver v0.3报警。怎么样解决呢？

![screen shot 2018-05-17 at 7 46 42 am](https://user-images.githubusercontent.com/21017389/40155297-7c2dc6c2-59c5-11e8-9c4f-f96ce7a3ef67.png)
![photo_2018-05-17_09-00-43](https://user-images.githubusercontent.com/21017389/40155298-7f4c009e-59c5-11e8-9871-18e90b506a67.jpg)

**Comment by lupos208** [comment]
同样的问题，大佬们解决下吧

**Comment by Esinchung** [comment]
估计等下次更新了

**Comment by andyhuai** [comment]
@kszym2002 换什么源，能贴出来吗？现在好多插件都这样了
